<?php

use Illuminate\Database\Seeder;

class ChartsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('charts')->insert(['airport_id' => 50, 'name' => 'AD2-LGAD-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 50, 'name' => 'AD2-LGAD-SID-1', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'KAM1B;KFN1J;TRL1D;ZAK1B' ]);
        DB::table('charts')->insert(['airport_id' => 50, 'name' => 'AD2-LGAD-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 50, 'name' => 'AD2-LGAD', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 49, 'name' => 'AD2-LGAL-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 49, 'name' => 'AD2-LGAL-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 49, 'name' => 'AD2-LGAL-IAC-1', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 49, 'name' => 'AD2-LGAL-IAC-2', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'NDB' ]);
        DB::table('charts')->insert(['airport_id' => 49, 'name' => 'AD2-LGAL-SID-1', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'GOLDO1B;IDILO1B;LMO1B' ]);
        DB::table('charts')->insert(['airport_id' => 49, 'name' => 'AD2-LGAL-SID-2', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'GOLDO1C;IDILO1C;LMO1C' ]);
        DB::table('charts')->insert(['airport_id' => 49, 'name' => 'AD2-LGAL-STAR-1', 'extension' => 'pdf', 'runway' => '07/25', 'tags' => 'GOLDO1A;IDILO1A;LMO1A' ]);
        DB::table('charts')->insert(['airport_id' => 49, 'name' => 'AD2-LGAL', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-AOC A-2', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-AOC B-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-APDC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-01', 'extension' => 'pdf', 'runway' => '03R', 'tags' => 'ILSx' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-02', 'extension' => 'pdf', 'runway' => '03R', 'tags' => 'ILSw' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-03', 'extension' => 'pdf', 'runway' => '03L', 'tags' => 'ILSx' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-04', 'extension' => 'pdf', 'runway' => '03L', 'tags' => 'ILSw' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-05', 'extension' => 'pdf', 'runway' => '21L', 'tags' => 'ILSx' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-06', 'extension' => 'pdf', 'runway' => '21L', 'tags' => 'ILSw' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-07', 'extension' => 'pdf', 'runway' => '21R', 'tags' => 'ILSx' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-08', 'extension' => 'pdf', 'runway' => '03R', 'tags' => 'ILSz' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-09', 'extension' => 'pdf', 'runway' => '03R', 'tags' => 'ILSy' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-10', 'extension' => 'pdf', 'runway' => '03L', 'tags' => 'ILSz' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-11', 'extension' => 'pdf', 'runway' => '03L', 'tags' => 'ILSy' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-12', 'extension' => 'pdf', 'runway' => '21L', 'tags' => 'ILSz' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-13', 'extension' => 'pdf', 'runway' => '21L', 'tags' => 'ILSy' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-14', 'extension' => 'pdf', 'runway' => '21R', 'tags' => 'ILSz' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-15', 'extension' => 'pdf', 'runway' => '03R', 'tags' => 'VOR' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-16', 'extension' => 'pdf', 'runway' => '03R', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-17', 'extension' => 'pdf', 'runway' => '03L', 'tags' => 'VOR' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-18', 'extension' => 'pdf', 'runway' => '03L', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-19', 'extension' => 'pdf', 'runway' => '21L', 'tags' => 'VOR' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-20', 'extension' => 'pdf', 'runway' => '21L', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-IAC-21', 'extension' => 'pdf', 'runway' => '21R', 'tags' => 'VOR' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-PATC-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-PATC-2', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-SID-01', 'extension' => 'pdf', 'runway' => '03R', 'tags' => 'ABLON2J;ASTOV2J;BIBEX1J;GENDO1J;KEA1J;KEPIR1J;NEVRA1J;PIKAD2J;RILIN2J;RIMAX1J;SOREV2J;VARIX1J;VELOP2J' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-SID-03', 'extension' => 'pdf', 'runway' => '03R', 'tags' => 'ABLON1E;ASTOV1E;BIBEX1E;GENDO1E;KEA1E;KEPIR1E;NEVRA1Y;PIKAD1E;RILIN1E;RIMAX1E;SOREV1E;VARIX1E;VELOP1E' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-SID-04', 'extension' => 'pdf', 'runway' => '03R', 'tags' => 'ABLON1T;ASTOV1T;BIBEX1T;GENDO1T;KEA1T;KEPIR1T;NEVRA1T;PIKAD1T;RILIN1T;RIMAX1T;SOREV1T;VARIX1T;VELOP1T' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-SID-05', 'extension' => 'pdf', 'runway' => '03L', 'tags' => 'ABLON2L;ASTOV2L;GENDO1L;KEA1L;KEPIR1L;NEVRA1L;PIKAD2L;RILIN2L;RIMAX1L;SOREV1L;VARIX1L;VELOP2L' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-SID-06', 'extension' => 'pdf', 'runway' => '03L', 'tags' => 'ABLON2D;ASTOV2D;PIKAD2D;RILIN2D;RIMAX1D;VELOP2D' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-SID-08', 'extension' => 'pdf', 'runway' => '03L', 'tags' => 'ABLON1K;ASTOV1K;KEA1K;KEPIR1K;NEVRA1N;PIKAD1K;RILIN1K;RIMAX1K;SOREV1K;SOREV1N;VARIX1K;VELOP1K' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-SID-09', 'extension' => 'pdf', 'runway' => '21R', 'tags' => 'ABLON1G;ASTOV1G;GENOD1G;KEA1G;KEPIR1G;NEVRA2G;PIKAD2G;RILIN2G;RIMAX1G;SOREV1G;VARIX1G;VELOP2G' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-SID-11', 'extension' => 'pdf', 'runway' => '21L', 'tags' => 'ABLON3F;ASTOV1F;BIBEX1F;GENDO1F;KEA1F;KEPIR1F;NEVRA2F;PIKAD2F;RILIN2F;RIMAX1F;SOREV1F;VARIX1F;VELOP2F' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-STAR-01', 'extension' => 'pdf', 'runway' => '03R/L', 'tags' => 'ABLON1C;ABLON1P;ASTOV1C;BADEL3C;BADEL3P;KEPIR2C;NEMES1C;NEVRA2C;PIKAD1C;RILIN1C;SOREV1C;VARIX2C;VELOP1C;XORKI1C;XORKI1P' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-STAR-03', 'extension' => 'pdf', 'runway' => '21R/L', 'tags' => 'ABLON1B;ASTOV1B;KEPIR1A;NEMES1B;NEVRA1A;PIKAD1B;RILIN1B;SOREV1B;VARIX1A;VARIX1B;VELOP1B;XORIK2B' ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-VEC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 48, 'name' => 'AD2-LGAV', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 46, 'name' => 'AD2-LGBL-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 46, 'name' => 'AD2-LGBL-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 46, 'name' => 'AD2-LGBL-IAC-1', 'extension' => 'pdf', 'runway' => '26', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 46, 'name' => 'AD2-LGBL-IAC-2', 'extension' => 'pdf', 'runway' => '26', 'tags' => 'ILS' ]);
        DB::table('charts')->insert(['airport_id' => 46, 'name' => 'AD2-LGBL-SID-1', 'extension' => 'pdf', 'runway' => '08', 'tags' => 'EVIKO1A;GARTA1A;LUSES1A;TGG2C;VAXUS1A' ]);
        DB::table('charts')->insert(['airport_id' => 46, 'name' => 'AD2-LGBL-SID-2', 'extension' => 'pdf', 'runway' => '26', 'tags' => 'EVIKO1B;GARTA1B;LUSES1B;TGG2F;VAXUS1B' ]);
        DB::table('charts')->insert(['airport_id' => 46, 'name' => 'AD2-LGBL-STAR-1', 'extension' => 'pdf', 'runway' => '26', 'tags' => 'EVIKO1C;EVIKO1H;GARTA1H;LUSES1H;PELIP1C;PELIP1H;TGG2J;TGG2H;VAXUS1H' ]);
        DB::table('charts')->insert(['airport_id' => 46, 'name' => 'AD2-LGBL', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 45, 'name' => 'AD2-LGEL-IAC-1', 'extension' => 'pdf', 'runway' => '36', 'tags' => 'ILSw' ]);
        DB::table('charts')->insert(['airport_id' => 45, 'name' => 'AD2-LGEL-IAC-2', 'extension' => 'pdf', 'runway' => '36', 'tags' => 'LLZw' ]);
        DB::table('charts')->insert(['airport_id' => 45, 'name' => 'AD2-LGEL-IAC-3', 'extension' => 'pdf', 'runway' => '36', 'tags' => 'VORw' ]);
        DB::table('charts')->insert(['airport_id' => 45, 'name' => 'AD2-LGEL-SID-1', 'extension' => 'pdf', 'runway' => '18', 'tags' => 'ABLON1U;DDM1U;KEA1U;KOR1U;KRO1U' ]);
        DB::table('charts')->insert(['airport_id' => 45, 'name' => 'AD2-LGEL-SID-2', 'extension' => 'pdf', 'runway' => '36', 'tags' => 'ABLON1V;DDM1V;KEA1V;KOR1V;KRO1V' ]);
        DB::table('charts')->insert(['airport_id' => 45, 'name' => 'AD2-LGEL', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 44, 'name' => 'AD2-LGHI-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 44, 'name' => 'AD2-LGHI-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 44, 'name' => 'AD2-LGHI-IAC-1', 'extension' => 'pdf', 'runway' => '01', 'tags' => 'NDB' ]);
        DB::table('charts')->insert(['airport_id' => 44, 'name' => 'AD2-LGHI-IAC-2', 'extension' => 'pdf', 'runway' => '01', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 44, 'name' => 'AD2-LGHI-SID-1', 'extension' => 'pdf', 'runway' => '01', 'tags' => 'MES1A;PANOX1A' ]);
        DB::table('charts')->insert(['airport_id' => 44, 'name' => 'AD2-LGHI-SID-2', 'extension' => 'pdf', 'runway' => '19', 'tags' => 'MES1B;PANOX1B' ]);
        DB::table('charts')->insert(['airport_id' => 44, 'name' => 'AD2-LGHI-STAR-1', 'extension' => 'pdf', 'runway' => '01/19', 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 44, 'name' => 'AD2-LGHI', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 43, 'name' => 'AD2-LGIK-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 43, 'name' => 'AD2-LGIK', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-IAC-1', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-IAC-2', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'VORa(CATA,B)' ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-IAC-3', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'VORb(CATC,D)' ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-IAC-4', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'VORc(circling)' ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-IAC-5', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'VORd(circling)' ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-SID-1', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'DIMIS1B;GARTA3B;KAS1B;KRK3B;LUSES1B;NIDRI1B;PIKOS1B;ROTSA1B;TUMBO1B;VJOSA1B' ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-SID-2', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'DIMIS1A;GARTA3A;KAS1A;KRK3A;LUSES1A;NIDRI1A;PIKOS1A;ROTSA1A;TUMBO1A;VJOSA1A' ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-STAR-1', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'GARTA1E;GARTA1F;KRK1E;KRK1F;ROTSA1E;ROTSA1F' ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO-STAR-2', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'GARTA1C;GARTA1D;KRK1C;ROTSA1C;ROTSA1D' ]);
        DB::table('charts')->insert(['airport_id' => 42, 'name' => 'AD2-LGIO', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-AOC A-2_2', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-IAC-1', 'extension' => 'pdf', 'runway' => '27', 'tags' => 'L/DME' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-IAC-2', 'extension' => 'pdf', 'runway' => '27', 'tags' => 'L/DME' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-IAC-3', 'extension' => 'pdf', 'runway' => '27', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-IAC-4', 'extension' => 'pdf', 'runway' => '09', 'tags' => 'VORb' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-IAC-5', 'extension' => 'pdf', 'runway' => '27', 'tags' => 'RNAV(GNSS)' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-SID-1', 'extension' => 'pdf', 'runway' => '09', 'tags' => 'BAVES1H;BAVES1K;EPALO1H;EPALO1J;EPALO1K;LABUX1H;NAVUS1H;NAVUS1J;NAVUS1K;OTREX2H;OTREX2K;SIT2H;SIT2K;XAVIS1H' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-SID-2', 'extension' => 'pdf', 'runway' => '27', 'tags' => 'EPALO1C;EPALO1F;EPALO1T;NAVUS1C;NAVUS1F;XAVIS1C' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-SID-3', 'extension' => 'pdf', 'runway' => '09', 'tags' => 'BAVES1E;DELAV1E;EPALO1E;NAVUS1E;OTREX1E;SIT1E;XAVIS1E' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-SID-4', 'extension' => 'pdf', 'runway' => '27', 'tags' => 'BAVES1D;DELAV1D;EPALO1D;NAVUS1D;OTREX2D;SIT2D;XAVIS1D' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-SID-5', 'extension' => 'pdf', 'runway' => '12', 'tags' => 'BAVES1S;EPALO1Q;EPALO1R;EPALO1S;LABUX1Q;NAVUS1Q;NAVUS1R;NAVUS1S;OTREX1S;SIT1Q;SIT1R;XAVIS1Q' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-SID-6', 'extension' => 'pdf', 'runway' => '30', 'tags' => 'BAVES1N;EPALO1N;EPALO1P;IRA1N;LABUX1N;NAVUS1N;OTREX1N;SIT1N;SIT1P;XAVIS1N' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-SID-7', 'extension' => 'pdf', 'runway' => '27', 'tags' => 'BAVES1C;LABUX1C;LABUX1T;OTREX3C;SIT3C;SIT3F;SIT3T' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-STAR-1', 'extension' => 'pdf', 'runway' => '27', 'tags' => 'BAVES1A;EPALO1A;EPALO1B;LABUX1A;LABUX1B;NAVUS1A;NAVUS1B;OTREX3A;SIT2A;SIT2B;XAVIS1A' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-STAR-2', 'extension' => 'pdf', 'runway' => '09', 'tags' => 'BAVES2L;EPALO2L;LABUX2L;NAVUS2;OTREX2L;SIT2L;TIPUS2L;XAVIS2L' ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-VEC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 41, 'name' => 'AD2-LGIR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 40, 'name' => 'AD2-LGKA-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 40, 'name' => 'AD2-LGKA-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 40, 'name' => 'AD2-LGKA-IAC-1', 'extension' => 'pdf', 'runway' => '12/30', 'tags' => 'VOR/DMECATA,B' ]);
        DB::table('charts')->insert(['airport_id' => 40, 'name' => 'AD2-LGKA-IAC-2', 'extension' => 'pdf', 'runway' => '12/30', 'tags' => 'VOR/DMECATC,D' ]);
        DB::table('charts')->insert(['airport_id' => 40, 'name' => 'AD2-LGKA-SID-1', 'extension' => 'pdf', 'runway' => '30', 'tags' => 'KOZ1L;TSL1L;YNN1L' ]);
        DB::table('charts')->insert(['airport_id' => 40, 'name' => 'AD2-LGKA-SID-2', 'extension' => 'pdf', 'runway' => '12', 'tags' => 'KOZ1G;TSL1G;YNN1G' ]);
        DB::table('charts')->insert(['airport_id' => 40, 'name' => 'AD2-LGKA', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-IAC-1', 'extension' => 'pdf', 'runway' => '02/20', 'tags' => 'NDBaCATA,B' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-IAC-2', 'extension' => 'pdf', 'runway' => '02/20', 'tags' => 'NDBbCATC' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-IAC-3', 'extension' => 'pdf', 'runway' => '02', 'tags' => 'VORzCATA,B' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-IAC-4', 'extension' => 'pdf', 'runway' => '02', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-IAC-5', 'extension' => 'pdf', 'runway' => '20', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-SID-1', 'extension' => 'pdf', 'runway' => '02', 'tags' => 'IXIMA1K;SOKRI2K' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-SID-2', 'extension' => 'pdf', 'runway' => '20', 'tags' => 'IXIMA1L;SOKRI2L' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-SID-3', 'extension' => 'pdf', 'runway' => '02', 'tags' => 'IXIMA1D;SOKRI1D' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-SID-4', 'extension' => 'pdf', 'runway' => '20', 'tags' => 'IXIMA1E;SOKRI1E' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-STAR-1', 'extension' => 'pdf', 'runway' => '02/20', 'tags' => 'IXIMA1A;SOKRI2A' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-STAR-2', 'extension' => 'pdf', 'runway' => '02', 'tags' => 'IXIMA1B;SOKRI1B' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC-STAR-3', 'extension' => 'pdf', 'runway' => '20', 'tags' => 'IXIMA1C;SOKRI1C' ]);
        DB::table('charts')->insert(['airport_id' => 39, 'name' => 'AD2-LGKC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-IAC-1', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'VORz' ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-IAC-2', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-IAC-3', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-SID-1', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'ARA3E;GARTA2E;KFN2E;LATAN3E;ROTSA1E;RUTOM3E' ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-SID-2', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'ARA2T;GARTA1T;ROTSA1T' ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-SID-3', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'ARA3K;ARA1L;GARTA2K;KFN2K;ROTSA1K' ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-STAR-1', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'ARA3J' ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-STAR-2', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'ARA2P;ARA2Q;ASTUS1P;LASKO1P' ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF-STAR-3', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'ARA2G;ARA2N;ASTUS1G;ASTUS1N;LASKO1G;LASKO1N' ]);
        DB::table('charts')->insert(['airport_id' => 38, 'name' => 'AD2-LGKF', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 37, 'name' => 'AD2-LGKJ-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 37, 'name' => 'AD2-LGKJ-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 37, 'name' => 'AD2-LGKJ', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 36, 'name' => 'AD2-LGKL-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 36, 'name' => 'AD2-LGKL-IAC-1', 'extension' => 'pdf', 'runway' => '35L', 'tags' => 'ILSz' ]);
        DB::table('charts')->insert(['airport_id' => 36, 'name' => 'AD2-LGKL-IAC-2', 'extension' => 'pdf', 'runway' => '35L', 'tags' => 'LLZz' ]);
        DB::table('charts')->insert(['airport_id' => 36, 'name' => 'AD2-LGKL-IAC-3', 'extension' => 'pdf', 'runway' => '35L', 'tags' => 'VORz' ]);
        DB::table('charts')->insert(['airport_id' => 36, 'name' => 'AD2-LGKL-SID-1', 'extension' => 'pdf', 'runway' => '35L', 'tags' => 'ETILI1A;RESPA1A;TRL1A' ]);
        DB::table('charts')->insert(['airport_id' => 36, 'name' => 'AD2-LGKL-SID-2', 'extension' => 'pdf', 'runway' => '17R', 'tags' => 'ETILI1B;ETILI1C;RESPA1B;SOKRI1M;SOKRI1N;TRL1B' ]);
        DB::table('charts')->insert(['airport_id' => 36, 'name' => 'AD2-LGKL-STAR-1', 'extension' => 'pdf', 'runway' => '35L', 'tags' => 'PLH1F;PLH1G;RESPA1F;RESPA1G;SOKRI1F;SOKRI1G' ]);
        DB::table('charts')->insert(['airport_id' => 36, 'name' => 'AD2-LGKL-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 36, 'name' => 'AD2-LGKL', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-AOC-A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-IAC-1', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-IAC-2', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-IAC-3', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => '(L)' ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-SID-1', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'GILOS1C;KOPAR3B;KOPAR3C;LARKI3B;RDS3B' ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-SID-2', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'GILOS1A;GILOS1D;KOPAR3A;LARKI3A;USINI2A;USINI2D' ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-STAR-1', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'ASIMI1J;GILOS1H;GILOS1J;KOPAR2H;KOPAR2J;LARKI2H;USINI2H' ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-STAR-2', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'GILOS1K;GILOS1L;KOPAR2K;KOPAR2L;LARKI2K;LARKI2L;USINI2K' ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 34, 'name' => 'AD2-LGKO', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 33, 'name' => 'AD2-LGKP-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 33, 'name' => 'AD2-LGKP-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 33, 'name' => 'AD2-LGKP-IAC-1', 'extension' => 'pdf', 'runway' => '12', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 33, 'name' => 'AD2-LGKP-IAC-2', 'extension' => 'pdf', 'runway' => '30', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 33, 'name' => 'AD2-LGKP-SID-1', 'extension' => 'pdf', 'runway' => '12', 'tags' => 'LIAKI1B;NIPIS1B;ROXOL1B;SIT1B;SOTIX1B;TIPAS1B' ]);
        DB::table('charts')->insert(['airport_id' => 33, 'name' => 'AD2-LGKP-SID-2', 'extension' => 'pdf', 'runway' => '30', 'tags' => 'LIAKI1A;NIPIS1A;ROXOL1A;SIT1A;SOTIX1A;TIPAS1A' ]);
        DB::table('charts')->insert(['airport_id' => 33, 'name' => 'AD2-LGKP', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-APDC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-01', 'extension' => 'pdf', 'runway' => '17/35', 'tags' => 'VORa' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-02', 'extension' => 'pdf', 'runway' => '17/35', 'tags' => 'VORb' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-03', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-04', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'VORu' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-05', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'VORv' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-06', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'VORw' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-07', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'VORx' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-08', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-09', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'VORz' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-10', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'La' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-IAC-11', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'RNAV(GNSS)' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-SID-1', 'extension' => 'pdf', 'runway' => '17', 'tags' => 'IDIMI1B;LATAN2B;LATAN2D;MALED1K;OLGAT2B;OLGAT2D;PARNA1B;RIPID1B;TIGRA2B;TIGRA2D;VARDI1B;YNN1B' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-SID-2', 'extension' => 'pdf', 'runway' => '17', 'tags' => 'OLGAT2N;TIGRA2' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-SID-3', 'extension' => 'pdf', 'runway' => '17', 'tags' => 'NIKRO2B;NIKRO2D' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-SID-4', 'extension' => 'pdf', 'runway' => '17', 'tags' => 'NIKRO1C' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-SID-5', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'IDIMI1F;LATAN2F;MALED1F;NIKRO2F;OLGAT2F;PARNA1F;RIPID1F;TIGRA2F;VARDI1F;YNN1F' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-SID-6', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'IDIMI1G;LATAN2G;MALED1L;NIKRO2G;PARNA1G;RIPID1G;TIGRA2G;VARDI1G;YNN1G' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-SID-7', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'IDIMI1V;LATAN2V;MALED1V;NIKRO2V;OLGAT2V;PARNA1V;RIPID1V;TIGRA2V;VARDI1V;YNN1V' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-STAR-1', 'extension' => 'pdf', 'runway' => '17/35', 'tags' => 'IDIMI1P;LATAN2P;NOSTO1P;PARNA1P;PITAS2P;TIGRA2P;YNN1P' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-STAR-2', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'LATAN2S;NOSTO1R;NOSTO1S;PITAS2S;TIGRA2R;TIGRA2S' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-STAR-3', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'IDIMI1J;LATAN2J;MALED1J;NOSTO1;PARNA1J;PITAS2C;PITAS2J;RIPID1J;TIGRA2J;VARDI1J;YNN1J' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-STAR-4', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'LATAN2T;MALED1T;NOSTO1T;PARNA1T;PITAS2T;RIPID1T;TIGRA2T;VARDI1T;YNN1T' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-STAR-5', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'BETAK1U;IDIMI1U;LATAN2U;MALED1U;NOSTO1U;PARNA1U;PITAS2U;RIPID1U;TIGRA1U;VARDI1U;YNN1U' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-STAR-6', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'MALED1A;PARNA1A;PITAS2A;TIGRA2A;VARDI1A;YNN1A' ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-VEC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 32, 'name' => 'AD2-LGKR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 31, 'name' => 'AD2-LGKS-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 31, 'name' => 'AD2-LGKS-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 31, 'name' => 'AD2-LGKS', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-APDC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-IAC-1', 'extension' => 'pdf', 'runway' => '05R', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-IAC-2', 'extension' => 'pdf', 'runway' => '05R', 'tags' => 'NDBz' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-IAC-3', 'extension' => 'pdf', 'runway' => '05R', 'tags' => 'NDBy' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-IAC-4', 'extension' => 'pdf', 'runway' => '23L', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-SID-1', 'extension' => 'pdf', 'runway' => '05R', 'tags' => 'AMALA1B;ASKOS1B;SOSUS1B' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-SID-2', 'extension' => 'pdf', 'runway' => '05R', 'tags' => 'AMALA1A;ASKOS1A;SOSUS1A;XERIS1A' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-SID-3', 'extension' => 'pdf', 'runway' => '05R', 'tags' => 'AMALA1N;ASKOS1N;SOSUS1N;XERIS1N' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-SID-4', 'extension' => 'pdf', 'runway' => '23L', 'tags' => 'AMALA1D;SOSUS1D' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-SID-5', 'extension' => 'pdf', 'runway' => '23L', 'tags' => 'AMALA1C;ASKOS1C;ASKOS1E;SOSUS1C;XERIS1C' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-SID-6', 'extension' => 'pdf', 'runway' => '23L', 'tags' => 'AMALA1L;ASKOS1L;SOSUS1L;XERIS1C1L' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-STAR-1', 'extension' => 'pdf', 'runway' => '05R', 'tags' => 'AMALA1H;ASKOS1H;LOPTI1H;SOSUS1H' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-STAR-2', 'extension' => 'pdf', 'runway' => '05R', 'tags' => 'AMALA1X;ASKOS1X;SOSUS1X' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-STAR-3', 'extension' => 'pdf', 'runway' => '23L', 'tags' => 'AMALA1J;ASKOS1J;LOPTI1J;SOSUS1J' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-STAR-4', 'extension' => 'pdf', 'runway' => '23L', 'tags' => 'AMALA1Y;ASKOS1Y;SOSUS1Y' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV-STAR-5', 'extension' => 'pdf', 'runway' => '05R/23L', 'tags' => 'AMALA1Z;ASKOS1Z;LOPTI1Z;SOSUS1Z' ]);
        DB::table('charts')->insert(['airport_id' => 30, 'name' => 'AD2-LGKV', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 29, 'name' => 'AD2-LGKY-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 29, 'name' => 'AD2-LGKY-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 29, 'name' => 'AD2-LGKY', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 28, 'name' => 'AD2-LGKZ-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 28, 'name' => 'AD2-LGKZ-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 28, 'name' => 'AD2-LGKZ-IAC-1', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'VORaCATA' ]);
        DB::table('charts')->insert(['airport_id' => 28, 'name' => 'AD2-LGKZ-IAC-2', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'VORbCATB' ]);
        DB::table('charts')->insert(['airport_id' => 28, 'name' => 'AD2-LGKZ-IAC-3', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'VORcCATC' ]);
        DB::table('charts')->insert(['airport_id' => 28, 'name' => 'AD2-LGKZ-SID-1', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'KAS1B;KOGIS1B' ]);
        DB::table('charts')->insert(['airport_id' => 28, 'name' => 'AD2-LGKZ-SID-2', 'extension' => 'pdf', 'runway' => '32', 'tags' => 'KAS1A;KOGIS1A' ]);
        DB::table('charts')->insert(['airport_id' => 28, 'name' => 'AD2-LGKZ-STAR-1', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'KOGIS1C' ]);
        DB::table('charts')->insert(['airport_id' => 28, 'name' => 'AD2-LGKZ', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 27, 'name' => 'AD2-LGLE-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 27, 'name' => 'AD2-LGLE-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 27, 'name' => 'AD2-LGLE', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 26, 'name' => 'AD2-LGLM-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 26, 'name' => 'AD2-LGLM-AOC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 26, 'name' => 'AD2-LGLM-IAC-1', 'extension' => 'pdf', 'runway' => '04R', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 26, 'name' => 'AD2-LGLM-IAC-2', 'extension' => 'pdf', 'runway' => '22L', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 26, 'name' => 'AD2-LGLM-SID-1', 'extension' => 'pdf', 'runway' => '04R', 'tags' => 'ALX2A;KOROS2A;KPL2A;MES2A;NILVA2A;PEREN2A' ]);
        DB::table('charts')->insert(['airport_id' => 26, 'name' => 'AD2-LGLM-SID-2', 'extension' => 'pdf', 'runway' => '22L', 'tags' => 'ALX2B;KOROS2B;KPL2B;MES2B;NILVA2B;PEREN2B' ]);
        DB::table('charts')->insert(['airport_id' => 26, 'name' => 'AD2-LGLM-STAR-1', 'extension' => 'pdf', 'runway' => '04R/22L', 'tags' => 'ALX1D;KOROS1C;KOROS1D;KPL1C;KPL1D;MES1D;NILVA1D;PEREN1D' ]);
        DB::table('charts')->insert(['airport_id' => 26, 'name' => 'AD2-LGLM', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-IAC-1', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'VORz' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-IAC-2', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'NDBz' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-IAC-3', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-SID-1', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'DIDIS1D;LETSO1D;NITSA1D;PEROK1D;PIDAX1D;VARIX1D' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-SID-2', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'DIDIS1C;NITSA1C;PIDAX1C;PEROK1C;VARIX1C' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-SID-3', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'DIDIS1E;LETSO1E;NITSA1E;PEROK1E;PIDAX1E;VARIX1E' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-SID-4', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'DIDIS1F;LETSO1F;NITSA1F;PEROK1F;PIDAX1F;VARIX1F' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-SID-5', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'DIDIS1G;NITSA1G;LETSO1G;PEROK1G;PIDAX1G;VARIX1G' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-STAR-1', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'DIDIS1A;LETSO1A;NITSA1A;PEROK1A;PIDAX1A;VARIX1P' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-STAR-2', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'DIDIS1T;LETSO1T;NITSA1T;PEROK1T;PIDAX1T;VARIX1T' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK-STAR-3', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'DIDIS1H;NITSA1H;PEROK1H;PIDAX1H;VARIX1H' ]);
        DB::table('charts')->insert(['airport_id' => 23, 'name' => 'AD2-LGMK', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 22, 'name' => 'AD2-LGML-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 22, 'name' => 'AD2-LGML-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 22, 'name' => 'AD2-LGML-IAC-1', 'extension' => 'pdf', 'runway' => '08/26', 'tags' => 'VOR/DMECATA,B' ]);
        DB::table('charts')->insert(['airport_id' => 22, 'name' => 'AD2-LGML-IAC-2', 'extension' => 'pdf', 'runway' => '08/26', 'tags' => 'LCATA,B' ]);
        DB::table('charts')->insert(['airport_id' => 22, 'name' => 'AD2-LGML-SID-1', 'extension' => 'pdf', 'runway' => '08', 'tags' => 'MIL1A' ]);
        DB::table('charts')->insert(['airport_id' => 22, 'name' => 'AD2-LGML-SID-2', 'extension' => 'pdf', 'runway' => '26', 'tags' => 'MIL1B' ]);
        DB::table('charts')->insert(['airport_id' => 22, 'name' => 'AD2-LGML', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 21, 'name' => 'AD2-LGMT-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 21, 'name' => 'AD2-LGMT-AOC A', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 21, 'name' => 'AD2-LGMT-IAC-1', 'extension' => 'pdf', 'runway' => '14', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 21, 'name' => 'AD2-LGMT-IAC-2', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'VOR/DMEL' ]);
        DB::table('charts')->insert(['airport_id' => 21, 'name' => 'AD2-LGMT-SID-1', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'LSV1A;LSV1B' ]);
        DB::table('charts')->insert(['airport_id' => 21, 'name' => 'AD2-LGMT-STAR-1', 'extension' => 'pdf', 'runway' => '14/32', 'tags' => 'MARIK1A;NILVA1A' ]);
        DB::table('charts')->insert(['airport_id' => 21, 'name' => 'AD2-LGMT-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 21, 'name' => 'AD2-LGMT', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 20, 'name' => 'AD2-LGNX-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 20, 'name' => 'AD2-LGNX-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 20, 'name' => 'AD2-LGNX', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 19, 'name' => 'AD2-LGPA-ADC_1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 19, 'name' => 'AD2-LGPA-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 19, 'name' => 'AD2-LGPA', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 18, 'name' => 'AD2-LGPL-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 18, 'name' => 'AD2-LGPL-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 18, 'name' => 'AD2-LGPL', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-IAC-1', 'extension' => 'pdf', 'runway' => '07L', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-IAC-2', 'extension' => 'pdf', 'runway' => '25R', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-IAC-3', 'extension' => 'pdf', 'runway' => '07L', 'tags' => 'NDBaCATA,B' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-IAC-4', 'extension' => 'pdf', 'runway' => '07L', 'tags' => 'NDBbCATC,D' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-SID-1', 'extension' => 'pdf', 'runway' => '07L', 'tags' => 'GARTA1C;KFN1C;MALED1C;RIPID2C;SOTEG3C' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-SID-2', 'extension' => 'pdf', 'runway' => '25R', 'tags' => 'GARTA2E;KFN1E;MALED1E;RIPID2E' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-SID-3', 'extension' => 'pdf', 'runway' => '07L', 'tags' => 'GARTA2H;KFN1H;MALED2H;RIPID2H;SOTEG2H' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-SID-4', 'extension' => 'pdf', 'runway' => '25R', 'tags' => 'GARTA2J;KFN1J;MALED1J;RIPID2J' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-STAR-1', 'extension' => 'pdf', 'runway' => '07L', 'tags' => 'GARTA1A;GARTA1B;KFN1A;MALED1A;MALED1B;RIPID1A;SOTEG1A' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-STAR-2', 'extension' => 'pdf', 'runway' => '25R', 'tags' => 'GARTA1D;KFN1D;MALED1D;SOTEG3D' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ-STAR-3', 'extension' => 'pdf', 'runway' => '07L', 'tags' => 'GARTA1G;KFN1G;MALED1G;RIPID1G;SOTEG2G' ]);
        DB::table('charts')->insert(['airport_id' => 17, 'name' => 'AD2-LGPZ', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-IAC-1', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'ILSy' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-IAC-2', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'ILSz' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-IAC-3', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-IAC-4', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'VORz' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-IAC-5', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-IAC-6', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'VORz' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-SID-1', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'ASIMI2A;VANES2A;LOKNA2A;ROXOL1A;ORVIS1A;NAVOK1A;IRBAX1A;NILAS1A;LAKAD1A;SOTIV1A;PIROX1A;BANRO3A' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-SID-2', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'ASIMI2L;VANES2L' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-SID-3', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'ASIMI2M;ASIMI2N;BANRO3M;IRBAX1M;LAKAD1M;LOKNA2M;NAVOK1M;NILAS1M;ORVIS1M;PIROX1M;ROXOL1M;SOTIV1M;VANES2M;VANES2N' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-SID-4', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'ASIMI2P;BANRO3P;IRBAX1P;LAKAD1P;LOKNA2P;NAVOK1P;NILAS1P;ORVIS1P;PIROX1P;ROXOL1P;SOTIV1P;VANES2P' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-SID-5', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'ASIMI2B;BANRO3B;IRBAX1B;LAKAD1B;LOKNA2B;NAVOK1B;NILAS1B;ORVIS1B;PIROX1B;ROXOL1B;VANES2B' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-SID-6', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'ASIMI2T;BANRO3T;IRBAX1T;LAKAD1T;LOKNA2T;NAVIK1T;NILAS1T;ORVIS1T;PIROX1T;ROXOL1T;SOTIV1T;VANES2T' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-SID-7', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'ASIMI2Q;BANRO3Q;IRBAX1Q;LAKAD1Q;LOKNA2Q;NAVIK1Q;NILAS1Q;ORVIS1Q;PIROX1Q;ROXOL1Q;VANES2Q' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-STAR-1', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'ASIMI2H;BANRO3H;IRBAX1H;LAKAD1H;LOKNA2H;NAVOK1H;NILAS1H;ORVIS1H;PIROX1H;ROXOL1H;SOTIV1H;VANES2H' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-STAR-2', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'ASIMI2D;ASIMI2F;BANRO3D;IRBAX1D;LAKAD1D;LOKNA2D;NAVOK1D;NILAS1D;ORVIS1D;PIROX1D;ROXOL1D;SOTIV1D;VANES2D;VANES2F' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-STAR-3', 'extension' => 'pdf', 'runway' => '25', 'tags' => 'ASIMI2G;ASIMI2J;BANRO3G;IRBAX1G;LAKAD1G;LOKNA2G;LOKNA2J;NAVOK1G;NILAS1G;ORVIS1G;PIROX1G;ROXOL1G;VANES2G;VANES2J' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-STAR-4', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'ASIMI2S;BANRO2R;BANRO2S;IRBAX1S;LAKAD1S;LOKNA2S;NAVOK1S;NILAS1S;ORVIS1S;PIROX1R;PIROX1S;ROXOL1S;SOTIV1S;VANES2S' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-STAR-5', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'ASIMI2C;BANRO2C;IRBAX1C;LAKAD1C;LOKNA2C;NAVOK1C;NILAS1C;ORVIS1C;PIROX1C;ROXOL1C;SOTIV1C;VANES2C' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-STAR-6', 'extension' => 'pdf', 'runway' => '07', 'tags' => 'IRBAX1E;LAKAD1E;NAVIK1E;NILAS1E;ORVIS1E;ROXOL1E' ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-VEC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 15, 'name' => 'AD2-LGRP', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 14, 'name' => 'AD2-LGRX-ADC_1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 14, 'name' => 'AD2-LGRX-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 14, 'name' => 'AD2-LGRX-IAC-1', 'extension' => 'pdf', 'runway' => '18R', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 14, 'name' => 'AD2-LGRX-IAC-2', 'extension' => 'pdf', 'runway' => '18R/36L', 'tags' => 'VORa' ]);
        DB::table('charts')->insert(['airport_id' => 14, 'name' => 'AD2-LGRX-SID-1', 'extension' => 'pdf', 'runway' => '18R', 'tags' => 'ENESI3L;GARTA3L;IXONI3L;KOR3L;NEMES4L;SOTEG2L;TRL3L' ]);
        DB::table('charts')->insert(['airport_id' => 14, 'name' => 'AD2-LGRX-SID-2', 'extension' => 'pdf', 'runway' => '36L', 'tags' => 'ENESI3M;GARTA3M;IXONI3M;KOR3M;NEMES4M;SOTEG2M;TRL3M' ]);
        DB::table('charts')->insert(['airport_id' => 14, 'name' => 'AD2-LGRX-STAR-1', 'extension' => 'pdf', 'runway' => '36L', 'tags' => 'ENESI3G;GARTA2G;IXONI3G;KOR3G;NEMES4G;ORTOS2G;SOTEG2G;TRL3G' ]);
        DB::table('charts')->insert(['airport_id' => 14, 'name' => 'AD2-LGRX-STAR-2', 'extension' => 'pdf', 'runway' => '18R', 'tags' => 'ENESI3H;GARTA2H;IXONI3H;KOR3H;NEMES4H;ORTOS2H;SOTEG2H;TRL3H' ]);
        DB::table('charts')->insert(['airport_id' => 14, 'name' => 'AD2-LGRX', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-IAC-1', 'extension' => 'pdf', 'runway' => '11', 'tags' => 'VORx' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-IAC-2', 'extension' => 'pdf', 'runway' => '29', 'tags' => 'VORw' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-IAC-3', 'extension' => 'pdf', 'runway' => '11', 'tags' => 'VORz' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-IAC-4', 'extension' => 'pdf', 'runway' => '29', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-SID-1', 'extension' => 'pdf', 'runway' => '11', 'tags' => 'BAVES1B;OTREX5B;PLH1D;RUSOS2B;SOKRI5B' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-SID-2', 'extension' => 'pdf', 'runway' => '29', 'tags' => 'BAVES1A;OTREX5A;PLH1C;RUSOS2A;SOKRI5A' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-SID-3', 'extension' => 'pdf', 'runway' => '11', 'tags' => 'RUSOS2H;SOKRI1H' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-SID-4', 'extension' => 'pdf', 'runway' => '11', 'tags' => 'BAVES1J;OTREX1J;PLH1J' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-SID-5', 'extension' => 'pdf', 'runway' => '29', 'tags' => 'RUSOS2K;SOKRI1K' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-SID-6', 'extension' => 'pdf', 'runway' => '29', 'tags' => 'BAVES1L;OTREX1L;PLH1L' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-STAR-1', 'extension' => 'pdf', 'runway' => '11', 'tags' => 'BAVES1E;MANOK2E;OTREX2E;PLH2E;RUSOS2E;SOKRI2E' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-STAR-2', 'extension' => 'pdf', 'runway' => '29', 'tags' => 'BAVES1F;MANOK2F;OTREX2F;PLH2F;RUSOS2F;SOKRI2F' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-STAR-3', 'extension' => 'pdf', 'runway' => '11', 'tags' => 'BAVES1W;MANOK2W;OTREX1W;PLH1M;PLH1W;RUSOS2W;SOKRI2W' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-STAR-4', 'extension' => 'pdf', 'runway' => '29', 'tags' => 'BAVES1X;MANOK2X;OTREX1X;PLH1X;RUSOS2X;SOKRI2X' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-STAR-5', 'extension' => 'pdf', 'runway' => '29', 'tags' => 'BAVES1G;MANOK2G;OTREX1G;PLH1G;RUSOS2G;SOKRI2G' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-STAR-6', 'extension' => 'pdf', 'runway' => '11', 'tags' => 'BAVES1V;MANOK1V;OTREX1;PLH1V;PLH1U;RUSOS1V;SOKRI1V;SOKRI1U' ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 13, 'name' => 'AD2-LGSA', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 11, 'name' => 'AD2-LGSK-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 11, 'name' => 'AD2-LGSK-AOC A', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 11, 'name' => 'AD2-LGSK-IAC-1', 'extension' => 'pdf', 'runway' => '02', 'tags' => 'L' ]);
        DB::table('charts')->insert(['airport_id' => 11, 'name' => 'AD2-LGSK-IAC-2', 'extension' => 'pdf', 'runway' => '20', 'tags' => 'L' ]);
        DB::table('charts')->insert(['airport_id' => 11, 'name' => 'AD2-LGSK-SID-1', 'extension' => 'pdf', 'runway' => '02', 'tags' => 'AGH1B;DILOP1B;KOROS1B;TSL1B' ]);
        DB::table('charts')->insert(['airport_id' => 11, 'name' => 'AD2-LGSK-SID-2', 'extension' => 'pdf', 'runway' => '20', 'tags' => 'AGH1A;DILOP1A;KOROS1A;TSL1A' ]);
        DB::table('charts')->insert(['airport_id' => 11, 'name' => 'AD2-LGSK-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 11, 'name' => 'AD2-LGSK', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM-AOC A', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM-IAC-1', 'extension' => 'pdf', 'runway' => '09/27', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM-IAC-2', 'extension' => 'pdf', 'runway' => '09/27', 'tags' => 'NDB' ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM-SID-1', 'extension' => 'pdf', 'runway' => '09/27', 'tags' => 'LARKI3B;ORMOS2B;URNIL2B' ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM-SID-2', 'extension' => 'pdf', 'runway' => '09', 'tags' => 'LARKI1D;ORMOS1D;URNIL1D' ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM-SID-3', 'extension' => 'pdf', 'runway' => '27', 'tags' => 'LARKI1E;ORMOS1E;URNIL1E' ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM-STAR-1', 'extension' => 'pdf', 'runway' => '09/27', 'tags' => 'LARKI2A;ORMOS1C;ORMOS2A;URNIL1C;URNIL2A' ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 10, 'name' => 'AD2-LGSM', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 9, 'name' => 'AD2-LGSO-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 9, 'name' => 'AD2-LGSO-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 9, 'name' => 'AD2-LGSO-IAC-1', 'extension' => 'pdf', 'runway' => '18/36', 'tags' => 'CIRCLINGCATA,B' ]);
        DB::table('charts')->insert(['airport_id' => 9, 'name' => 'AD2-LGSO-SID-1', 'extension' => 'pdf', 'runway' => '18', 'tags' => 'KEA1B' ]);
        DB::table('charts')->insert(['airport_id' => 9, 'name' => 'AD2-LGSO-SID-2', 'extension' => 'pdf', 'runway' => '36', 'tags' => 'KEA1A' ]);
        DB::table('charts')->insert(['airport_id' => 9, 'name' => 'AD2-LGSO', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-IAC-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-IAC-2', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-IAC-3', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-IAC-4', 'extension' => 'pdf', 'runway' => '16L/34R', 'tags' => 'VORa(circling)' ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-IAC-5', 'extension' => 'pdf', 'runway' => '16L/34R', 'tags' => 'VORb(circling)' ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-IAC-6', 'extension' => 'pdf', 'runway' => '16L', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-IAC-7', 'extension' => 'pdf', 'runway' => '16L', 'tags' => 'VORz' ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-SID-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-SID-2', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-SID-3', 'extension' => 'pdf', 'runway' => '34R', 'tags' => 'GIVIS1X;IRBEG1X;KUPIS1X;MADEX1X;NETIS1X;SNI1X;UVRIT1X' ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-SID-4', 'extension' => 'pdf', 'runway' => '16L', 'tags' => 'GIVIS1W;IRBEG1E;IRBEG1W;KUPIS1E;MADEX1E;MADEX1W;NETIS1E;NETIS1W;SNI1E;UVRIT1E' ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-STAR-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-STAR-2', 'extension' => 'pdf', 'runway' => '34R', 'tags' => 'BIKNI1A;GIVIS1A;IRBEG1A;PEXAN1A;UVRIT1A' ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR-STAR-3', 'extension' => 'pdf', 'runway' => '16L', 'tags' => 'BIKNI1C;GIVIS1C;IRBEG1C;PEXAN1C;UVRIT1C' ]);
        DB::table('charts')->insert(['airport_id' => 8, 'name' => 'AD2-LGSR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 7, 'name' => 'AD2-LGST-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 7, 'name' => 'AD2-LGST-AOC A', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 7, 'name' => 'AD2-LGST-IAC-1', 'extension' => 'pdf', 'runway' => '23', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 7, 'name' => 'AD2-LGST-SID-1', 'extension' => 'pdf', 'runway' => '05', 'tags' => 'AMAXI2K;DELAV2K;LABUX1K;MOKIS2K;SIT2K;VEGES2K;XAVIS2K' ]);
        DB::table('charts')->insert(['airport_id' => 7, 'name' => 'AD2-LGST-SID-2', 'extension' => 'pdf', 'runway' => '23', 'tags' => 'AMAXI2V;DELAV2V;LABUX1V;MOKIS2V;SIT2V;VEGES2V;XAVIS2V' ]);
        DB::table('charts')->insert(['airport_id' => 7, 'name' => 'AD2-LGST-STAR-1', 'extension' => 'pdf', 'runway' => '23', 'tags' => 'AMAXI2H;DELAV1J;LABUX1J;MOKIS2H;SIT2H;VEGES2H;XAVIS2H;XAVIS2J' ]);
        DB::table('charts')->insert(['airport_id' => 7, 'name' => 'AD2-LGST', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 6, 'name' => 'AD2-LGSY-IAC-1', 'extension' => 'pdf', 'runway' => '17', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 6, 'name' => 'AD2-LGSY-SID-1', 'extension' => 'pdf', 'runway' => '17', 'tags' => 'KOROS1H;KOROS1J;NEVRA1E;SKP1C' ]);
        DB::table('charts')->insert(['airport_id' => 6, 'name' => 'AD2-LGSY-SID-2', 'extension' => 'pdf', 'runway' => '35', 'tags' => 'KOROS1F;KOROS1G;NEVRA1D;SKP1B' ]);
        DB::table('charts')->insert(['airport_id' => 6, 'name' => 'AD2-LGSY-STAR-1', 'extension' => 'pdf', 'runway' => '17', 'tags' => 'AMISI1A;ATROX1A;ATROX1B;ETEKA11;URUDI1A' ]);
        DB::table('charts')->insert(['airport_id' => 6, 'name' => 'AD2-LGSY-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 6, 'name' => 'AD2-LGSY', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-AOC A-2', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-IAC-1', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ILSCATI' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-IAC-10', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'VORa' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-IAC-11', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'VORb' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-IAC-2', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ILSCATII' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-IAC-3', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-IAC-6', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'VORz' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-IAC-7', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'VORy' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-IAC-8', 'extension' => 'pdf', 'runway' => '10', 'tags' => 'ILS/DMECATI' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-IAC-9', 'extension' => 'pdf', 'runway' => '10', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-PATC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-1', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'TSL3B' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-10', 'extension' => 'pdf', 'runway' => '28R', 'tags' => 'TSL4F;TSL4E' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-2', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'TSL3A' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-3', 'extension' => 'pdf', 'runway' => '10', 'tags' => 'ALIKO1C;ARNAS3C;EDASI1C;FSK4C;LEKPO1C;LOPOS3C;ODIKO1C' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-4', 'extension' => 'pdf', 'runway' => '10', 'tags' => 'ARNAS3G;TSL1C' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-5', 'extension' => 'pdf', 'runway' => '28', 'tags' => 'ALIKO1E;ARNAS3E;EDASI1E;FSK3E;LEKPO1E;LOPOS3E;ODIKO1E' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-6', 'extension' => 'pdf', 'runway' => '28', 'tags' => 'TSL3F;TSL3E' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-7', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ALIKO1B;ARNAS3B;EDASI1B;FSK4B;LEKPO1B;LOPOS3B;ODIKO1B' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-8', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'ALIKO1A;ARNAS3A;EDASI1A;FSK4A;LEKPO1A;LOPOS3A;ODIKO1A;OSMOS1A' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SID-9', 'extension' => 'pdf', 'runway' => '10L', 'tags' => 'TSL2C;ARNAS4G' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-STAR-1', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ALIKO1L;ARNAS2L;EDASI1L;FSK1L;LEKPO1L;LOPOS2L;ODIKO1L;OSMOS1L' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-STAR-2', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ALIKO2F;ARNAS3F;EDASI2F;LEKPO2F;LOPOS3F;OSMOS2F' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-STAR-3', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'ALIKO1P;ARNAS1P;EDASI1P;FSK3P;LEKPO1P;LOPOS1P;ODIKO1P;OSMOS1P' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-STAR-4', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'ALIKO2H;ARNAS2H;EDASI2H;LEKPO2H;LOPOS2H;OSMOS2H' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-STAR-5', 'extension' => 'pdf', 'runway' => '10', 'tags' => 'ALIKO1D;ARNAS3D;EDASI1D;FSK3D;LEKPO1D;LOPOS3D;ODIKO1D;OSMOS1D' ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-SUP-0217', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-VEC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS-VFR', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 3, 'name' => 'AD2-LGTS', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-ADC', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-AOC A-1', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-IAC-1', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-IAC-2', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'VOR/DME' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-IAC-3', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'NDBz' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-IAC-4', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'NDBz' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-IAC-5', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'NDBy' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-IAC-6', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'NDBy' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-IAC-7', 'extension' => 'pdf', 'runway' => '16/34', 'tags' => 'NDBaCATA,B' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-IAC-8', 'extension' => 'pdf', 'runway' => '16/34', 'tags' => 'NDBbCATA,B' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-SID-1', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ARA5H;ENESI1H;KFN4C;OSDES2H' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-SID-2', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'ARA3D;ENESI1D;KFN3D;OSDES2D' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-SID-3', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ARA2F;ENESI1F;KFN2K' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-SID-4', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'ARA2L;ENESI1L;KFN2G;KFN1L' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-SID-5', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ARA1X;KFN1X' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-SID-6', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'ARA1R;KFN1R' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-STAR-1', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ARA4B;KFN3B' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-STAR-2', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ASTUS2A;ASTUS1B;ASTUS2C;LASKO1B;LASKO2C' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-STAR-3', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'ARA4A;ARA3S;KFN3A;KFN2S' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-STAR-4', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'ASTUS1K;ASTUS2F;ASTUS2J;ASTUS2D;LASKO1K;LASKO2F;LASKO2J' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-STAR-5', 'extension' => 'pdf', 'runway' => '34', 'tags' => 'ARA1C;KFN1F' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA-STAR-6', 'extension' => 'pdf', 'runway' => '16', 'tags' => 'ARA1M;KFN1H' ]);
        DB::table('charts')->insert(['airport_id' => 1, 'name' => 'AD2-LGZA', 'extension' => 'pdf', 'runway' => null, 'tags' => null ]);
    }
}
