<?php

use Illuminate\Database\Seeder;

class SidTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sids')->insert([ 'airport_id' => '1', 'runway' => '16', 'point' => 'ARA','name' => 'ARA 5H','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '1', 'runway' => '34', 'point' => 'ARA','name' => 'ARA 3D','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '1', 'runway' => '16', 'point' => 'ENESI','name' => 'ENESI 1H','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '1', 'runway' => '34', 'point' => 'ENESI','name' => 'ENESI 1D','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '1', 'runway' => '16', 'point' => 'OSDES','name' => 'OSDES 2H','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '1', 'runway' => '34', 'point' => 'OSDES','name' => 'OSDES 2D','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '1', 'runway' => '16', 'point' => 'KFN','name' => 'KFN 1X','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '1', 'runway' => '34', 'point' => 'KFN','name' => 'KFN 3D','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'ALIKO','name' => 'ALIKO 1B','initial_flight_level' => 'FL80','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'ALIKO','name' => 'ALIKO 1A','initial_flight_level' => 'FL80','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'ARNAS','name' => 'ARNAS 3B','initial_flight_level' => 'FL80','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'ARNAS','name' => 'ARNAS 3A','initial_flight_level' => 'FL80','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '10', 'point' => 'ARNAS','name' => 'ARNAS 4G','initial_flight_level' => 'FL80','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'EDASI','name' => 'EDASI 1B','initial_flight_level' => 'FL80','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'EDASI','name' => 'EDASI 1A','initial_flight_level' => 'FL80','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'FSK','name' => 'FSK 4B','initial_flight_level' => 'FL80','release_flight_level' => 'FL240']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'FSK','name' => 'FSK 4A','initial_flight_level' => 'FL80','release_flight_level' => 'FL240']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'LEKPO','name' => 'LEKPO 1B','initial_flight_level' => 'FL80','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'LEKPO','name' => 'LEKPO 1A','initial_flight_level' => 'FL80','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'LOPOS','name' => 'LOPOS 3B','initial_flight_level' => 'FL80','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'LOPOS','name' => 'LOPOS 3A','initial_flight_level' => 'FL80','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'ODIKO','name' => 'ODIKO 1B','initial_flight_level' => 'FL80','release_flight_level' => 'FL240']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'ODIKO','name' => 'ODIKO 1A','initial_flight_level' => 'FL80','release_flight_level' => 'FL240']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'TSL','name' => 'TSL 3B','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'TSL','name' => 'TSL 3A','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '10', 'point' => 'TSL','name' => 'TSL 2C','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '28', 'point' => 'TSL','name' => 'TSL 4F','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'OSMOS','name' => 'OSMOS 1A','initial_flight_level' => 'FL80','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '10C', 'point' => 'AGH','name' => 'AGH 1D']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'AGH','name' => 'AGH 1C']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '10C', 'point' => 'ATV','name' => 'ATV 1D']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'ATV','name' => 'ATV 1C']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '10C', 'point' => 'IXONI','name' => 'IXONI 1D']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'IXONI','name' => 'IXONI 1C']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '10C', 'point' => 'OLIDA','name' => 'OLIDA 1D']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'OLIDA','name' => 'OLIDA 1C']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '10C', 'point' => 'SKP','name' => 'SKP 1G']);
        DB::table('sids')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'SKP','name' => 'SKP 1F']);
        DB::table('sids')->insert([ 'airport_id' => '6', 'runway' => '17', 'point' => 'KOROS','name' => 'KOROS 1H']);
        DB::table('sids')->insert([ 'airport_id' => '6', 'runway' => '35', 'point' => 'KOROS','name' => 'KOROS 1F']);
        DB::table('sids')->insert([ 'airport_id' => '6', 'runway' => '17', 'point' => 'NEVRA','name' => 'NEVRA 1E']);
        DB::table('sids')->insert([ 'airport_id' => '6', 'runway' => '35', 'point' => 'NEVRA','name' => 'NEVRA 1D']);
        DB::table('sids')->insert([ 'airport_id' => '6', 'runway' => '17', 'point' => 'SKP','name' => 'SKP 1C']);
        DB::table('sids')->insert([ 'airport_id' => '6', 'runway' => '35', 'point' => 'SKP','name' => 'SKP 1B']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '05', 'point' => 'AMAXI','name' => 'AMAXI 2K']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'AMAXI','name' => 'AMAXI 2V']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '05', 'point' => 'DELAV','name' => 'DELAV 2K']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'DELAV','name' => 'DELAV 2V']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '05', 'point' => 'LABUX','name' => 'LABUX 1K']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'LABUX','name' => 'LABUX 1V']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '05', 'point' => 'MOKIS','name' => 'MOKIS 2K']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'MOKIS','name' => 'MOKIS 2V']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '05', 'point' => 'SIT','name' => 'SIT 2K']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'SIT','name' => 'SIT 2V']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '05', 'point' => 'VEGES','name' => 'VEGES 2K']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'VEGES','name' => 'VEGES 2V']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '05', 'point' => 'XAVIS','name' => 'XAVIS 2K']);
        DB::table('sids')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'XAVIS','name' => 'XAVIS 2V']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'GIVIS','name' => 'GIVIS 1W']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'GIVIS','name' => 'GIVIS 1X']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'IRBEG','name' => 'IRBEG 1E']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'IRBEG','name' => 'IRBEG 1X']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'KUPIS','name' => 'KUPIS 1E']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'KUPIS','name' => 'KUPIS 1X']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'MADEX','name' => 'MADEX 1E']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'MADEX','name' => 'MADEX 1X']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'NETIS','name' => 'NETIS 1W']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'NETIS','name' => 'NETIS 1X']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'UVRIT','name' => 'UVRIT 1E']);
        DB::table('sids')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'UVRIT','name' => 'UVRIT 1X']);
        DB::table('sids')->insert([ 'airport_id' => '9', 'runway' => '18', 'point' => 'KEA','name' => 'KEA 1B']);
        DB::table('sids')->insert([ 'airport_id' => '9', 'runway' => '36', 'point' => 'KEA','name' => 'KEA 1A']);
        DB::table('sids')->insert([ 'airport_id' => '10', 'runway' => '09', 'point' => 'LARKI','name' => 'LARKI 1D']);
        DB::table('sids')->insert([ 'airport_id' => '10', 'runway' => '27', 'point' => 'LARKI','name' => 'LARKI 1E']);
        DB::table('sids')->insert([ 'airport_id' => '10', 'runway' => '09', 'point' => 'ORMOS','name' => 'ORMOS 1D']);
        DB::table('sids')->insert([ 'airport_id' => '10', 'runway' => '27', 'point' => 'ORMOS','name' => 'ORMOS 1E']);
        DB::table('sids')->insert([ 'airport_id' => '10', 'runway' => '09', 'point' => 'URNIL','name' => 'URNIL 1D']);
        DB::table('sids')->insert([ 'airport_id' => '10', 'runway' => '27', 'point' => 'URNIL','name' => 'URNIL 1E']);
        DB::table('sids')->insert([ 'airport_id' => '11', 'runway' => '02', 'point' => 'AGH','name' => 'AGH 1B','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '11', 'runway' => '20', 'point' => 'AGH','name' => 'AGH 1A','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '11', 'runway' => '02', 'point' => 'DILOP','name' => 'DILOP 1B','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '11', 'runway' => '20', 'point' => 'DILOP','name' => 'DILOP 1A','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '11', 'runway' => '02', 'point' => 'KOROS','name' => 'KOROS 1B','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '11', 'runway' => '20', 'point' => 'KOROS','name' => 'KOROS 1A','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '11', 'runway' => '02', 'point' => 'TSL','name' => 'TSL 1B','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '11', 'runway' => '20', 'point' => 'TSL','name' => 'TSL 1A','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'BAVES','name' => 'BAVES 1B','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'BAVES','name' => 'BAVES 1A','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'OTREX','name' => 'OTREX 5B','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'OTREX','name' => 'OTREX 5A','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'PLH','name' => 'PLH 1D','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'PLH','name' => 'PLH 1C','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'RUSOS','name' => 'RUSOS 2B','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'RUSOS','name' => 'RUSOS 2A','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'SOKRI','name' => 'SOKRI 5B','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'SOKRI','name' => 'SOKRI 5A','initial_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'ENESI','name' => 'ENESI 3L']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'ENESI','name' => 'ENESI 3M']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'GARTA','name' => 'GARTA 3L']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'GARTA','name' => 'GARTA 3M']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'IXONI','name' => 'IXONI 3L']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'IXONI','name' => 'IXONI 3M']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'KOR','name' => 'KOR 3L']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'KOR','name' => 'KOR 3M']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'NEMES','name' => 'NEMES 4L']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'NEMES','name' => 'NEMES 4M']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'SOTEG','name' => 'SOTEG 2L']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'SOTEG','name' => 'SOTEG 2M']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'TRL','name' => 'TRL 3L']);
        DB::table('sids')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'TRL','name' => 'TRL 3M']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'ASIMI','name' => 'ASIMI 2A','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'ASIMI','name' => 'ASIMI 2B','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'BANRO','name' => 'BANRO 3A','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'BANRO','name' => 'BANRO 3B','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'IRBAX','name' => 'IRBAX 1A','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'IRBAX','name' => 'IRBAX 1B','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'LAKAD','name' => 'LAKAD 1A','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'LAKAD','name' => 'LAKAD 1B','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'LOKNA','name' => 'LOKNA 2A','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'LOKNA','name' => 'LOKNA 2B','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'NAVOK','name' => 'NAVOK 1A','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'NAVOK','name' => 'NAVOK 1B','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'NILAS','name' => 'NILAS 1A','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'NILAS','name' => 'NILAS 1B','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'ORVIS','name' => 'ORVIS 1A','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'ORVIS','name' => 'ORVIS 1B','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'PIROX','name' => 'PIROX 1A','initial_flight_level' => 'FL120','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'PIROX','name' => 'PIROX 1B','initial_flight_level' => 'FL120','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'ROXOL','name' => 'ROXOL 1A','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'ROXOL','name' => 'ROXOL 1B','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'SOTIV','name' => 'SOTIV 1A','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'SOTIV','name' => 'SOTIV 1T','initial_flight_level' => 'FL120','release_flight_level' => 'FL130']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'VANES','name' => 'VANES 2A','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'VANES','name' => 'VANES 2B','initial_flight_level' => 'FL120','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '16', 'runway' => '08', 'point' => 'RDS','name' => 'RDS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '16', 'runway' => '26', 'point' => 'RDS','name' => 'RDS 1A']);
        DB::table('sids')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'GARTA','name' => 'GARTA 1C']);
        DB::table('sids')->insert([ 'airport_id' => '17', 'runway' => '25R', 'point' => 'GARTA','name' => 'GARTA 2E']);
        DB::table('sids')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'KFN','name' => 'KFN 1C']);
        DB::table('sids')->insert([ 'airport_id' => '17', 'runway' => '25R', 'point' => 'KFN','name' => 'KFN 1E']);
        DB::table('sids')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'MALED','name' => 'MALED 1C']);
        DB::table('sids')->insert([ 'airport_id' => '17', 'runway' => '25R', 'point' => 'MALED','name' => 'MALED 1E']);
        DB::table('sids')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'RIPID','name' => 'RIPID 2C']);
        DB::table('sids')->insert([ 'airport_id' => '17', 'runway' => '25R', 'point' => 'RIPID','name' => 'RIPID 2E']);
        DB::table('sids')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'SOTEG','name' => 'SOTEG 2H']);
        DB::table('sids')->insert([ 'airport_id' => '21', 'runway' => '14', 'point' => 'LSV','name' => 'LSV 1B','initial_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '21', 'runway' => '32', 'point' => 'LSV','name' => 'LSV 1A','initial_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '22', 'runway' => '08', 'point' => 'MIL','name' => 'MIL 1A']);
        DB::table('sids')->insert([ 'airport_id' => '22', 'runway' => '26', 'point' => 'MIL','name' => 'MIL 1B']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'DIDIS','name' => 'DIDIS 1C','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '16', 'point' => 'DIDIS','name' => 'DIDIS 1E','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'NITSA','name' => 'NITSA 1C','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '16', 'point' => 'NITSA','name' => 'NITSA 1E','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'PEROK','name' => 'PEROK 1C','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '16', 'point' => 'PEROK','name' => 'PEROK 1E','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'PIDAX','name' => 'PIDAX 1C','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '16', 'point' => 'PIDAX','name' => 'PIDAX 1E','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'VARIX','name' => 'VARIX 1C','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '16', 'point' => 'VARIX','name' => 'VARIX 1E','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'LETSO','name' => 'LETSO 1D','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '23', 'runway' => '16', 'point' => 'LETSO','name' => 'LETSO 1E','initial_flight_level' => 'FL90']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'ALX','name' => 'ALX 2A']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'ALX','name' => 'ALX 2B']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'KOROS','name' => 'KOROS 2A']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'KOROS','name' => 'KOROS 2B']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'KPL','name' => 'KPL 2A']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'KPL','name' => 'KPL 2B']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'MES','name' => 'MES 2A']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'MES','name' => 'MES 2B']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'NILVA','name' => 'NILVA 2A']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'NILVA','name' => 'NILVA 2B']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'PEREN','name' => 'PEREN 2A']);
        DB::table('sids')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'PEREN','name' => 'PEREN 2B']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '14', 'point' => 'KAS','name' => 'KAS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '32', 'point' => 'KAS','name' => 'KAS 1A']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '14', 'point' => 'KOGIS','name' => 'KOGI 1B']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '32', 'point' => 'KOGIS','name' => 'KOGI 1A']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '14', 'point' => 'LOPOS','name' => 'KOGI 1B']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '32', 'point' => 'LOPOS','name' => 'KOGI 1A']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '14', 'point' => 'LSA','name' => 'KOGI 1B']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '32', 'point' => 'LSA','name' => 'KOGI 1A']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '14', 'point' => 'PIKOS','name' => 'KOGI 1B']);
        DB::table('sids')->insert([ 'airport_id' => '28', 'runway' => '32', 'point' => 'PIKOS','name' => 'KOGI 1A']);
        DB::table('sids')->insert([ 'airport_id' => '30', 'runway' => '05R', 'point' => 'AMALA','name' => 'AMALA 1B']);
        DB::table('sids')->insert([ 'airport_id' => '30', 'runway' => '23L', 'point' => 'AMALA','name' => 'AMALA 1D']);
        DB::table('sids')->insert([ 'airport_id' => '30', 'runway' => '05R', 'point' => 'ASKOS','name' => 'ASKOS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '30', 'runway' => '23L', 'point' => 'ASKOS','name' => 'ASKOS 1C']);
        DB::table('sids')->insert([ 'airport_id' => '30', 'runway' => '05R', 'point' => 'SOSUS','name' => 'SOSUS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '30', 'runway' => '23L', 'point' => 'SOSUS','name' => 'SOSUS 1D']);
        DB::table('sids')->insert([ 'airport_id' => '30', 'runway' => '05R', 'point' => 'XERIS','name' => 'XERIS 1A']);
        DB::table('sids')->insert([ 'airport_id' => '30', 'runway' => '23L', 'point' => 'XERIS','name' => 'XERIS 1C']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'IDIMI','name' => 'IDIMI 1F','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'IDIMI','name' => 'IDIMI 1B','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'LATAN','name' => 'LATAN 2F','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'LATAN','name' => 'LATAN 2B','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'MALED','name' => 'MALED 1F','initial_flight_level' => 'FL80','release_flight_level' => 'FL110']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'MALED','name' => 'MALED 1K','initial_flight_level' => 'FL80','release_flight_level' => 'FL110']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'NIKRO','name' => 'NIKRO 2F','initial_flight_level' => 'FL80','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'NIKRO','name' => 'NIKRO 1C','initial_flight_level' => 'FL80','release_flight_level' => 'FL120']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'OLGAT','name' => 'OLGAT 2F','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'OLGAT','name' => 'OLGAT 2B','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'PARNA','name' => 'PARNA 1F','initial_flight_level' => 'FL80','release_flight_level' => 'FL110']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'PARNA','name' => 'PARNA 1B','initial_flight_level' => 'FL80','release_flight_level' => 'FL110']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'RIPID','name' => 'RIPID 1F','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'RIPID','name' => 'RIPID 1B','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'TIGRA','name' => 'TIGRA 2F','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'TIGRA','name' => 'TIGRA 2B','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'VARDI','name' => 'VARDI 1F','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'VARDI','name' => 'VARDI 1B','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'YNN','name' => 'YNN 1F','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '32', 'runway' => '17', 'point' => 'YNN','name' => 'YNN 1B','initial_flight_level' => 'FL80']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '12', 'point' => 'LIAKI','name' => 'LIAKI 1B']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '30', 'point' => 'LIAKI','name' => 'LIAKI 1A']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '12', 'point' => 'NIPIS','name' => 'NIPIS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '30', 'point' => 'NIPIS','name' => 'NIPIS 1A']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '12', 'point' => 'ROXOL','name' => 'ROXOL 1B']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '30', 'point' => 'ROXOL','name' => 'ROXOL 1A']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '12', 'point' => 'SIT','name' => 'SIT 1B']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '30', 'point' => 'SIT','name' => 'SIT 1A']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '12', 'point' => 'SOTIX','name' => 'SOTIX 1B']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '30', 'point' => 'SOTIX','name' => 'SOTIX 1A']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '12', 'point' => 'TIPAS','name' => 'TIPAS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '33', 'runway' => '30', 'point' => 'TIPAS','name' => 'TIPAS 1A']);
        DB::table('sids')->insert([ 'airport_id' => '34', 'runway' => '14', 'point' => 'GILOS','name' => 'GILOS 1C']);
        DB::table('sids')->insert([ 'airport_id' => '34', 'runway' => '32', 'point' => 'GILOS','name' => 'GILOS 1D']);
        DB::table('sids')->insert([ 'airport_id' => '34', 'runway' => '14', 'point' => 'KOPAR','name' => 'KOPAR 3C']);
        DB::table('sids')->insert([ 'airport_id' => '34', 'runway' => '32', 'point' => 'KOPAR','name' => 'KOPAR 3A']);
        DB::table('sids')->insert([ 'airport_id' => '34', 'runway' => '14', 'point' => 'LARKI','name' => 'LARKI 3B']);
        DB::table('sids')->insert([ 'airport_id' => '34', 'runway' => '32', 'point' => 'LARKI','name' => 'LARKI 3A']);
        DB::table('sids')->insert([ 'airport_id' => '34', 'runway' => '14', 'point' => 'RDS','name' => 'RDS 3B']);
        DB::table('sids')->insert([ 'airport_id' => '34', 'runway' => '32', 'point' => 'USINI','name' => 'USINI 2D']);
        DB::table('sids')->insert([ 'airport_id' => '36', 'runway' => '17R', 'point' => 'ETILI','name' => 'ETILI 1B']);
        DB::table('sids')->insert([ 'airport_id' => '36', 'runway' => '35L', 'point' => 'ETILI','name' => 'ETILI 1A']);
        DB::table('sids')->insert([ 'airport_id' => '36', 'runway' => '17R', 'point' => 'RESPA','name' => 'RESPA 1B']);
        DB::table('sids')->insert([ 'airport_id' => '36', 'runway' => '35L', 'point' => 'RESPA','name' => 'RESPA 1A']);
        DB::table('sids')->insert([ 'airport_id' => '36', 'runway' => '17R', 'point' => 'SOKRI','name' => 'SOKRI 1M']);
        DB::table('sids')->insert([ 'airport_id' => '36', 'runway' => '35L', 'point' => 'SOKRI','name' => 'SOKRI 1V']);
        DB::table('sids')->insert([ 'airport_id' => '36', 'runway' => '17R', 'point' => 'TRL','name' => 'TRL 1B']);
        DB::table('sids')->insert([ 'airport_id' => '36', 'runway' => '35L', 'point' => 'TRL','name' => 'TRL 1A']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '14', 'point' => 'ARA','name' => 'ARA 3K','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '32', 'point' => 'ARA','name' => 'ARA 3E','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '14', 'point' => 'GARTA','name' => 'GARTA 2K','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '32', 'point' => 'GARTA','name' => 'GARTA 2E','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '14', 'point' => 'KFN','name' => 'KFN 2K','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '32', 'point' => 'KFN','name' => 'KFN 2E','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '14', 'point' => 'ROTSA','name' => 'ROTSA 1K','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '32', 'point' => 'ROTSA','name' => 'ROTSA 1E','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '32', 'point' => 'LATAN','name' => 'LATAN 3E','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '38', 'runway' => '32', 'point' => 'RUTOM','name' => 'RUTOM 3E','initial_flight_level' => '8000ft']);
        DB::table('sids')->insert([ 'airport_id' => '39', 'runway' => '02', 'point' => 'IXIMA','name' => 'IXIMA 1D']);
        DB::table('sids')->insert([ 'airport_id' => '39', 'runway' => '20', 'point' => 'IXIMA','name' => 'IXIMA 1E']);
        DB::table('sids')->insert([ 'airport_id' => '39', 'runway' => '02', 'point' => 'SOKRI','name' => 'SOKRI 1D']);
        DB::table('sids')->insert([ 'airport_id' => '39', 'runway' => '20', 'point' => 'SOKRI','name' => 'SOKRI 1E']);
        DB::table('sids')->insert([ 'airport_id' => '40', 'runway' => '12', 'point' => 'KOZ','name' => 'KOZ 1G']);
        DB::table('sids')->insert([ 'airport_id' => '40', 'runway' => '30', 'point' => 'KOZ','name' => 'KOZ 1L']);
        DB::table('sids')->insert([ 'airport_id' => '40', 'runway' => '12', 'point' => 'TSL','name' => 'TSL 1G']);
        DB::table('sids')->insert([ 'airport_id' => '40', 'runway' => '30', 'point' => 'TSL','name' => 'TSL 1L']);
        DB::table('sids')->insert([ 'airport_id' => '40', 'runway' => '12', 'point' => 'YNN','name' => 'YNN 1G']);
        DB::table('sids')->insert([ 'airport_id' => '40', 'runway' => '30', 'point' => 'YNN','name' => 'YNN 1L']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'BAVES','name' => 'BAVES 1C','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'BAVES','name' => 'BAVES 1H','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '12', 'point' => 'BAVES','name' => 'BAVES 1S','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '30', 'point' => 'BAVES','name' => 'BAVES 1N','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'EPALO','name' => 'EPALO 1C','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'EPALO','name' => 'EPALO 1H','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '12', 'point' => 'EPALO','name' => 'EPALO 1Q','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '30', 'point' => 'EPALO','name' => 'EPALO 1N','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'LABUX','name' => 'LABUX 1C','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'LABUX','name' => 'LABUX 1H','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '12', 'point' => 'LABUX','name' => 'LABUX 1Q','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '30', 'point' => 'LABUX','name' => 'LABUX 1N','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'NAVUS','name' => 'NAVUS 1C','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'NAVUS','name' => 'NAVUS 1H','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '12', 'point' => 'NAVUS','name' => 'NAVUS 1Q','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '30', 'point' => 'NAVUS','name' => 'NAVUS 1N','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'OTREX','name' => 'OTREX 3C','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'OTREX','name' => 'OTREX 2H','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '12', 'point' => 'OTREX','name' => 'OTREX 1S','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '30', 'point' => 'OTREX','name' => 'OTREX 1N','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'SIT','name' => 'SIT 3C','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'SIT','name' => 'SIT 2H','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '12', 'point' => 'SIT','name' => 'SIT 1Q','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '30', 'point' => 'SIT','name' => 'SIT 1N','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'XAVIS','name' => 'XAVIS 1C','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'XAVIS','name' => 'XAVIS 1H','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '12', 'point' => 'XAVIS','name' => 'XAVIS 1Q','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '30', 'point' => 'XAVIS','name' => 'XAVIS 1N','initial_flight_level' => 'FL100','release_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'DELAV','name' => 'DELAV 1D','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'DELAV','name' => 'DELAV 1E','initial_flight_level' => 'FL100','release_flight_level' => 'FL150']);
        DB::table('sids')->insert([ 'airport_id' => '41', 'runway' => '30', 'point' => 'IRA','name' => 'IRA 1N','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'DIMIS','name' => 'DIMIS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'DIMIS','name' => 'DIMIS 1A']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'GARTA','name' => 'GARTA 3B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'GARTA','name' => 'GARTA 3A']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'KAS','name' => 'KAS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'KAS','name' => 'KAS 1A']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'KRK','name' => 'KRK 3B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'KRK','name' => 'KRK 3A']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'LUSES','name' => 'LUSES 1B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'LUSES','name' => 'LUSES 1A']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'NIDRI','name' => 'NIDRI 1B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'NIDRI','name' => 'NIDRI 1A']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'PIKOS','name' => 'PIKOS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'PIKOS','name' => 'PIKOS 1A']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'ROTSA','name' => 'ROTSA 1B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'ROTSA','name' => 'ROTSA 1A']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'TUMBO','name' => 'TUMBO 1B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'TUMBO','name' => 'TUMBO 1A']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'VJOSA','name' => 'VJOSA 1B']);
        DB::table('sids')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'VJOSA','name' => 'VJOSA 1A']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'MES','name' => 'MES 1A']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '19', 'point' => 'MES','name' => 'MES 1B']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'LMO','name' => 'MES 1A']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '19', 'point' => 'LMO','name' => 'MES 1B']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'LUPIS','name' => 'MES 1A']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '19', 'point' => 'LUPIS','name' => 'MES 1B']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'MARIK','name' => 'MES 1A']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '19', 'point' => 'MARIK','name' => 'MES 1B']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'PIPEN','name' => 'MES 1A']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '19', 'point' => 'PIPEN','name' => 'MES 1B']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'SITRU','name' => 'MES 1A']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '19', 'point' => 'SITRU','name' => 'MES 1B']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'PANOX','name' => 'PANOX 1A']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '19', 'point' => 'PANOX','name' => 'PANOX 1B']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'OLIDA','name' => 'PANOX 1A']);
        DB::table('sids')->insert([ 'airport_id' => '44', 'runway' => '19', 'point' => 'OLIDA','name' => 'PANOX 1B']);
        DB::table('sids')->insert([ 'airport_id' => '45', 'runway' => '18', 'point' => 'ABLON','name' => 'ABLON 1U']);
        DB::table('sids')->insert([ 'airport_id' => '45', 'runway' => '36', 'point' => 'ABLON','name' => 'ABLON 1V']);
        DB::table('sids')->insert([ 'airport_id' => '45', 'runway' => '18', 'point' => 'DDM','name' => 'DDM 1U']);
        DB::table('sids')->insert([ 'airport_id' => '45', 'runway' => '36', 'point' => 'DDM','name' => 'DDM 1V']);
        DB::table('sids')->insert([ 'airport_id' => '45', 'runway' => '18', 'point' => 'KEA','name' => 'KEA 1U']);
        DB::table('sids')->insert([ 'airport_id' => '45', 'runway' => '36', 'point' => 'KEA','name' => 'KEA 1V']);
        DB::table('sids')->insert([ 'airport_id' => '45', 'runway' => '18', 'point' => 'KOR','name' => 'KOR 1U']);
        DB::table('sids')->insert([ 'airport_id' => '45', 'runway' => '36', 'point' => 'KOR','name' => 'KOR 1V']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '08', 'point' => 'EVIKO','name' => 'EVIKO 1A']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'EVIKO','name' => 'EVIKO 1B']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '08', 'point' => 'GARTA','name' => 'GARTA 1A']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'GARTA','name' => 'GARTA 1B']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '08', 'point' => 'LUSES','name' => 'LUSES 1A']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'LUSES','name' => 'LUSES 1B']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '08', 'point' => 'TGG','name' => 'TGG 2C']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'TGG','name' => 'TGG 2F']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '08', 'point' => 'VAXUS','name' => 'VAXUS 1A']);
        DB::table('sids')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'VAXUS','name' => 'VAXUS 1B']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'ABLON','name' => 'ABLON 1T','initial_flight_level' => 'FL100','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'ABLON','name' => 'ABLON 2D','initial_flight_level' => 'FL100','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'ABLON','name' => 'ABLON 3F','initial_flight_level' => '6000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'ABLON','name' => 'ABLON 1G','initial_flight_level' => '5000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'ASTOV','name' => 'ASTOV 1T','initial_flight_level' => '9000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'ASTOV','name' => 'ASTOV 2D','initial_flight_level' => 'FL100','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'ASTOV','name' => 'ASTOV 1F','initial_flight_level' => '6000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'ASTOV','name' => 'ASTOV 1G','initial_flight_level' => '5000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'BIBEX','name' => 'BIBEX 1T','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'BIBEX','name' => 'BIBEX 1F','initial_flight_level' => '6000ft']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'GENDO','name' => 'GENDO 1T','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'GENDO','name' => 'GENDO 1L','initial_flight_level' => '7000ft']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'GENDO','name' => 'GENDO 1F','initial_flight_level' => '6000ft']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'GENDO','name' => 'GENDO 1G','initial_flight_level' => '5000ft']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'KEA','name' => 'KEA 1T','initial_flight_level' => 'FL100']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'KEA','name' => 'KEA 1L','initial_flight_level' => '7000ft']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'KEA','name' => 'KEA 1F','initial_flight_level' => '6000ft']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'KEA','name' => 'KEA 1G','initial_flight_level' => '5000ft']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'KEPIR','name' => 'KEPIR 1T','initial_flight_level' => '8000ft','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'KEPIR','name' => 'KEPIR 1L','initial_flight_level' => '7000ft','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'KEPIR','name' => 'KEPIR 1F','initial_flight_level' => '6000ft','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'KEPIR','name' => 'KEPIR 1G','initial_flight_level' => '5000ft','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'NEVRA','name' => 'NEVRA 1T','initial_flight_level' => 'FL100','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'NEVRA','name' => 'NEVRA 1M','initial_flight_level' => 'FL130','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'NEVRA','name' => 'NEVRA 1H','initial_flight_level' => 'FL130','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'NEVRA','name' => 'NEVRA 2G','initial_flight_level' => '5000ft','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'PIKAD','name' => 'PIKAD 1T','initial_flight_level' => '9000ft','release_flight_level' => 'FL240']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'PIKAD','name' => 'PIKAD 2D','initial_flight_level' => 'FL100','release_flight_level' => 'FL240']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'PIKAD','name' => 'PIKAD 2F','initial_flight_level' => '6000ft','release_flight_level' => 'FL240']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'PIKAD','name' => 'PIKAD 2G','initial_flight_level' => '5000ft','release_flight_level' => 'FL240']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'RILIN','name' => 'RILIN 1T','initial_flight_level' => 'FL100','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'RILIN','name' => 'RILIN 2D','initial_flight_level' => 'FL100','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'RILIN','name' => 'RILIN 2F','initial_flight_level' => '6000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'RILIN','name' => 'RILIN 2G','initial_flight_level' => '5000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'RIMAX','name' => 'RIMAX 1T','initial_flight_level' => 'FL120','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'RIMAX','name' => 'RIMAX 1D','initial_flight_level' => 'FL120','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'RIMAX','name' => 'RIMAX 1F','initial_flight_level' => '6000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'RIMAX','name' => 'RIMAX 1G','initial_flight_level' => '5000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'SOREV','name' => 'SOREV 1T','initial_flight_level' => '7000ft','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'SOREV','name' => 'SOREV 1L','initial_flight_level' => '7000ft','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'SOREV','name' => 'SOREV 1F','initial_flight_level' => '6000ft','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'SOREV','name' => 'SOREV 1G','initial_flight_level' => '5000ft','release_flight_level' => 'FL170']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'VARIX','name' => 'VARIX 1T','initial_flight_level' => '7000ft','release_flight_level' => 'FL190']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'VARIX','name' => 'VARIX 1L','initial_flight_level' => '7000ft','release_flight_level' => 'FL190']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'VARIX','name' => 'VARIX 1F','initial_flight_level' => '6000ft','release_flight_level' => 'FL190']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'VARIX','name' => 'VARIX 1G','initial_flight_level' => '5000ft','release_flight_level' => 'FL190']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'VELOP','name' => 'VELOP 1T','initial_flight_level' => 'FL100','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'VELOP','name' => 'VELOP 2D','initial_flight_level' => '9000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'VELOP','name' => 'VELOP 2F','initial_flight_level' => '6000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'VELOP','name' => 'VELOP 2G','initial_flight_level' => '5000ft','release_flight_level' => 'FL160']);
        DB::table('sids')->insert([ 'airport_id' => '49', 'runway' => '07', 'point' => 'GOLDO','name' => 'GOLDO 1B','initial_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '49', 'runway' => '25', 'point' => 'GOLDO','name' => 'GOLDO 1C','initial_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '49', 'runway' => '07', 'point' => 'IDILO','name' => 'IDILO 1B','initial_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '49', 'runway' => '25', 'point' => 'IDILO','name' => 'IDILO 1C','initial_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '49', 'runway' => '07', 'point' => 'LMO','name' => 'LMO 1B','initial_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '49', 'runway' => '25', 'point' => 'LMO','name' => 'LMO 1C','initial_flight_level' => 'FL140']);
        DB::table('sids')->insert([ 'airport_id' => '50', 'runway' => '16', 'point' => 'KAM','name' => 'KAM 1B']);
        DB::table('sids')->insert([ 'airport_id' => '50', 'runway' => '16', 'point' => 'KFN','name' => 'KFN 1J']);
        DB::table('sids')->insert([ 'airport_id' => '50', 'runway' => '16', 'point' => 'TRL','name' => 'TRL 1D']);
        DB::table('sids')->insert([ 'airport_id' => '50', 'runway' => '16', 'point' => 'ZAK','name' => 'ZAK 1B']);
    }
}
