<?php

use Illuminate\Database\Seeder;

class StarsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stars')->insert([ 'airport_id' => '1', 'runway' => '16', 'point' => 'ARA', 'name' => 'ARA 4B']);
        DB::table('stars')->insert([ 'airport_id' => '1', 'runway' => '34', 'point' => 'ARA', 'name' => 'ARA 3S']);
        DB::table('stars')->insert([ 'airport_id' => '1', 'runway' => '16', 'point' => 'ASTUS', 'name' => 'ASTUS 1B']);
        DB::table('stars')->insert([ 'airport_id' => '1', 'runway' => '34', 'point' => 'ASTUS', 'name' => 'ASTUS 1K']);
        DB::table('stars')->insert([ 'airport_id' => '1', 'runway' => '16', 'point' => 'KFN', 'name' => 'KFN 3B']);
        DB::table('stars')->insert([ 'airport_id' => '1', 'runway' => '34', 'point' => 'KFN', 'name' => 'KFN 2S']);
        DB::table('stars')->insert([ 'airport_id' => '1', 'runway' => '16', 'point' => 'LASKO', 'name' => 'LASKO 1B']);
        DB::table('stars')->insert([ 'airport_id' => '1', 'runway' => '34', 'point' => 'LASKO', 'name' => 'LASKO 1K']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'ALIKO', 'name' => 'ALIKO 1L','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'ALIKO', 'name' => 'ALIKO 1P','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'ARNAS', 'name' => 'ARNAS 2L','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'ARNAS', 'name' => 'ARNAS 1P','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'EDASI', 'name' => 'EDASI 1L','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'EDASI', 'name' => 'EDASI 1P','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'FSK', 'name' => 'FSK 1L','entry_flight_level' => 'FL120']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'FSK', 'name' => 'FSK 3P','entry_flight_level' => 'FL120']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'LEKPO', 'name' => 'LEKPO 1L','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'LEKPO', 'name' => 'LEKPO 1P','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'LOPOS', 'name' => 'LOPOS 2L','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'LOPOS', 'name' => 'LOPOS 1P','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'ODIKO', 'name' => 'ODIKO 1L','entry_flight_level' => 'FL120']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'ODIKO', 'name' => 'ODIKO 1P','entry_flight_level' => 'FL120']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '16', 'point' => 'OSMOS', 'name' => 'OSMOS 1L','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '3', 'runway' => '34', 'point' => 'OSMOS', 'name' => 'OSMOS 1P','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'AGH', 'name' => 'AGH 3E']);
        DB::table('stars')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'ATV', 'name' => 'ATV 3A']);
        DB::table('stars')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'I28', 'name' => 'I28 CW']);
        DB::table('stars')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'IXONI', 'name' => 'IXONI 3A']);
        DB::table('stars')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'OLIDA', 'name' => 'OLIDA 3A']);
        DB::table('stars')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'R05', 'name' => 'R05 5L']);
        DB::table('stars')->insert([ 'airport_id' => '5', 'runway' => '28C', 'point' => 'SKP', 'name' => 'SKP 3D']);
        DB::table('stars')->insert([ 'airport_id' => '6', 'runway' => '17', 'point' => 'AMISI', 'name' => 'AMISI 1A']);
        DB::table('stars')->insert([ 'airport_id' => '6', 'runway' => '17', 'point' => 'ATROX', 'name' => 'ATROX 1A']);
        DB::table('stars')->insert([ 'airport_id' => '6', 'runway' => '17', 'point' => 'ETEKA', 'name' => 'ETEKA 1A']);
        DB::table('stars')->insert([ 'airport_id' => '6', 'runway' => '17', 'point' => 'URUDI', 'name' => 'URUDI 1A']);
        DB::table('stars')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'AMAXI', 'name' => 'AMAXI 2H']);
        DB::table('stars')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'DELAV', 'name' => 'DELAV 1J']);
        DB::table('stars')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'LABUX', 'name' => 'LABUX 1J']);
        DB::table('stars')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'MOKIS', 'name' => 'MOKIS 2H']);
        DB::table('stars')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'SIT', 'name' => 'SIT 2H']);
        DB::table('stars')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'VEGES', 'name' => 'VEGES 2H']);
        DB::table('stars')->insert([ 'airport_id' => '7', 'runway' => '23', 'point' => 'XAVIS', 'name' => 'XAVIS 2H']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'BINKI', 'name' => 'BINKI 1C','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'BINKI', 'name' => 'BINKI 1A','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'GIVIS', 'name' => 'GIVIS 1C','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'GIVIS', 'name' => 'GIVIS 1A','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'IRBEG', 'name' => 'IRBEG 1C','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'IRBEG', 'name' => 'IRBEG 1A','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'PEXAN', 'name' => 'PEXAN 1C','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'PEXAN', 'name' => 'PEXAN 1A','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '16L', 'point' => 'UVRIT', 'name' => 'UVRIT 1C','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '8', 'runway' => '34R', 'point' => 'UVRIT', 'name' => 'UVRIT 1A','entry_flight_level' => 'FL70']);
        DB::table('stars')->insert([ 'airport_id' => '10', 'runway' => '09', 'point' => 'LARKI', 'name' => 'LARKI 2A']);
        DB::table('stars')->insert([ 'airport_id' => '10', 'runway' => '27', 'point' => 'LARKI', 'name' => 'LARKI 2A']);
        DB::table('stars')->insert([ 'airport_id' => '10', 'runway' => '09', 'point' => 'ORMOS', 'name' => 'ORMOS 2A']);
        DB::table('stars')->insert([ 'airport_id' => '10', 'runway' => '27', 'point' => 'ORMOS', 'name' => 'ORMOS 2A']);
        DB::table('stars')->insert([ 'airport_id' => '10', 'runway' => '09', 'point' => 'URNIL', 'name' => 'URNIL 2A']);
        DB::table('stars')->insert([ 'airport_id' => '10', 'runway' => '27', 'point' => 'URNIL', 'name' => 'URNIL 2A']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'BAVES', 'name' => 'BAVES 1W']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'BAVES', 'name' => 'BAVES 1G']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'MANOK', 'name' => 'MANOK 2W']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'MANOK', 'name' => 'MANOK 2G']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'OTREX', 'name' => 'OTREX 1W']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'OTREX', 'name' => 'OTREX 1G']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'PLH', 'name' => 'PLH 1W']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'PLH', 'name' => 'PLH 1G']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'RUSOS', 'name' => 'RUSOS 2W']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'RUSOS', 'name' => 'RUSOS 2G']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '11', 'point' => 'SOKRI', 'name' => 'SOKRI 2W']);
        DB::table('stars')->insert([ 'airport_id' => '13', 'runway' => '29', 'point' => 'SOKRI', 'name' => 'SOKRI 2G']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'ENESI', 'name' => 'ENESI 3H']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'ENESI', 'name' => 'ENESI 3G']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'GARTA', 'name' => 'GARTA 2H']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'GARTA', 'name' => 'GARTA 2G']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'IXONI', 'name' => 'IXONI 3H']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'IXONI', 'name' => 'IXONI 3G']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'KOR', 'name' => 'KOR 3H']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'KOR', 'name' => 'KOR 3G']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'NEMES', 'name' => 'NEMES 4H']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'NEMES', 'name' => 'NEMES 4G']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'ORTOS', 'name' => 'ORTOS 2H']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'ORTOS', 'name' => 'ORTOS 2G']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'SOTEG', 'name' => 'SOTEG 2H']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'SOTEG', 'name' => 'SOTEG 2G']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '18R', 'point' => 'TRL', 'name' => 'TRL 3H']);
        DB::table('stars')->insert([ 'airport_id' => '14', 'runway' => '36L', 'point' => 'TRL', 'name' => 'TRL 3G']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'ASIMI', 'name' => 'ASIMI 2S','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'ASIMI', 'name' => 'ASIMI 2D','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'BANRO', 'name' => 'BANRO 2S','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'BANRO', 'name' => 'BANRO 3D','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'IRBAX', 'name' => 'IRBAX 1S','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'IRBAX', 'name' => 'IRBAX 1D','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'LAKAD', 'name' => 'LAKAD 1S','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'LAKAD', 'name' => 'LAKAD 1D','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'LOKNA', 'name' => 'LOKNA 2S','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'LOKNA', 'name' => 'LOKNA 2D','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'NAVOK', 'name' => 'NAVOK 1S','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'NAVOK', 'name' => 'NAVOK 1D','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'NILAS', 'name' => 'NILAS 1S','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'NILAS', 'name' => 'NILAS 1D','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'ORVIS', 'name' => 'ORVIS 1S','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'ORVIS', 'name' => 'ORVIS 1D','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'PIROX', 'name' => 'PIROX 1S','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'PIROX', 'name' => 'PIROX 1D','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'ROXOL', 'name' => 'ROXOL 1S','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'ROXOL', 'name' => 'ROXOL 1D','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'SOTIV', 'name' => 'SOTIV 1S','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'SOTIV', 'name' => 'SOTIV 1D','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '07', 'point' => 'VANES', 'name' => 'VANES 2S','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '15', 'runway' => '25', 'point' => 'VANES', 'name' => 'VANES 2D','entry_flight_level' => 'FL130']);
        DB::table('stars')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'GARTA', 'name' => 'GARTA 1A']);
        DB::table('stars')->insert([ 'airport_id' => '17', 'runway' => '25R', 'point' => 'GARTA', 'name' => 'GARTA 1D']);
        DB::table('stars')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'KFN', 'name' => 'KFN 1A']);
        DB::table('stars')->insert([ 'airport_id' => '17', 'runway' => '25R', 'point' => 'KFN', 'name' => 'KFN 1D']);
        DB::table('stars')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'MALED', 'name' => 'MALED 1A']);
        DB::table('stars')->insert([ 'airport_id' => '17', 'runway' => '25R', 'point' => 'MALED', 'name' => 'MALED 1D']);
        DB::table('stars')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'RIPID', 'name' => 'RIPID 1A']);
        DB::table('stars')->insert([ 'airport_id' => '17', 'runway' => '07L', 'point' => 'SOTEG', 'name' => 'SOTEG 1A']);
        DB::table('stars')->insert([ 'airport_id' => '17', 'runway' => '25R', 'point' => 'SOTEG', 'name' => 'SOTEG 3D']);
        DB::table('stars')->insert([ 'airport_id' => '21', 'runway' => '14', 'point' => 'MARIK', 'name' => 'MARIK 1A']);
        DB::table('stars')->insert([ 'airport_id' => '21', 'runway' => '32', 'point' => 'MARIK', 'name' => 'MARIK 1A']);
        DB::table('stars')->insert([ 'airport_id' => '21', 'runway' => '14', 'point' => 'NILVA', 'name' => 'NILVA 1A']);
        DB::table('stars')->insert([ 'airport_id' => '21', 'runway' => '32', 'point' => 'NILVA', 'name' => 'NILVA 1A']);
        DB::table('stars')->insert([ 'airport_id' => '21', 'runway' => '14', 'point' => 'OLIDA', 'name' => 'OLIDA']);
        DB::table('stars')->insert([ 'airport_id' => '21', 'runway' => '32', 'point' => 'OLIDA', 'name' => 'OLIDA']);
        DB::table('stars')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'DIDIS', 'name' => 'DIDIS 1A']);
        DB::table('stars')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'LETSO', 'name' => 'LETSO 1A']);
        DB::table('stars')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'NITSA', 'name' => 'NITSA 1A']);
        DB::table('stars')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'PEROK', 'name' => 'PEROK 1A']);
        DB::table('stars')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'PIDAX', 'name' => 'PIDAX 1A']);
        DB::table('stars')->insert([ 'airport_id' => '23', 'runway' => '34', 'point' => 'VARIX', 'name' => 'VARIX 1P']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'ALX', 'name' => 'ALX 1D']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'ALX', 'name' => 'ALX 1D']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'KOROS', 'name' => 'KOROS 1C']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'KOROS', 'name' => 'KOROS 1D']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'KPL', 'name' => 'KPL 1D']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'KPL', 'name' => 'KPL 1C']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'MES', 'name' => 'MES 1D']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'MES', 'name' => 'MES 1D']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'NILVA', 'name' => 'NILVA 1D']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'NILVA', 'name' => 'NILVA 1D']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '04R', 'point' => 'PEREN', 'name' => 'PEREN 1D']);
        DB::table('stars')->insert([ 'airport_id' => '26', 'runway' => '22L', 'point' => 'PEREN', 'name' => 'PEREN 1D']);
        DB::table('stars')->insert([ 'airport_id' => '28', 'runway' => '14', 'point' => 'KOGIS', 'name' => 'KOGIS 1C']);
        DB::table('stars')->insert([ 'airport_id' => '28', 'runway' => '32', 'point' => 'KOGIS', 'name' => 'KOGIS 1C']);
        DB::table('stars')->insert([ 'airport_id' => '28', 'runway' => '14', 'point' => 'LOPOS', 'name' => 'LOPOS']);
        DB::table('stars')->insert([ 'airport_id' => '28', 'runway' => '32', 'point' => 'LOPOS', 'name' => 'LOPOS']);
        DB::table('stars')->insert([ 'airport_id' => '28', 'runway' => '14', 'point' => 'LSA', 'name' => 'LSA']);
        DB::table('stars')->insert([ 'airport_id' => '28', 'runway' => '32', 'point' => 'LSA', 'name' => 'LSA']);
        DB::table('stars')->insert([ 'airport_id' => '28', 'runway' => '14', 'point' => 'PIKOS', 'name' => 'PIKOS']);
        DB::table('stars')->insert([ 'airport_id' => '28', 'runway' => '32', 'point' => 'PIKOS', 'name' => 'PIKOS']);
        DB::table('stars')->insert([ 'airport_id' => '30', 'runway' => '05R', 'point' => 'AMALA', 'name' => 'AMALA 1X']);
        DB::table('stars')->insert([ 'airport_id' => '30', 'runway' => '23L', 'point' => 'AMALA', 'name' => 'AMALA 1Y']);
        DB::table('stars')->insert([ 'airport_id' => '30', 'runway' => '05R', 'point' => 'ASKOS', 'name' => 'ASKOS 1X']);
        DB::table('stars')->insert([ 'airport_id' => '30', 'runway' => '23L', 'point' => 'ASKOS', 'name' => 'ASKOS 1Y']);
        DB::table('stars')->insert([ 'airport_id' => '30', 'runway' => '05R', 'point' => 'LOPTI', 'name' => 'LOPTI 1H']);
        DB::table('stars')->insert([ 'airport_id' => '30', 'runway' => '23L', 'point' => 'LOPTI', 'name' => 'LOPTI 1J']);
        DB::table('stars')->insert([ 'airport_id' => '30', 'runway' => '05R', 'point' => 'SOSUS', 'name' => 'SOSUS 1X']);
        DB::table('stars')->insert([ 'airport_id' => '30', 'runway' => '23L', 'point' => 'SOSUS', 'name' => 'SOSUS 1Y']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'BETAK', 'name' => 'BETAK 1U']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'IDIMI', 'name' => 'IDIMI 1J']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'LATAN', 'name' => 'LATAN 2J']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'MALED', 'name' => 'MALED 1U','entry_flight_level' => 'FL120']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'NOSTO', 'name' => 'NOSTO 1J']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'PARNA', 'name' => 'PARNA 1U','entry_flight_level' => 'FL120']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'PITAS', 'name' => 'PITAS 2J','entry_flight_level' => 'FL110']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'RIPID', 'name' => 'RIPID 1U']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'TIGRA', 'name' => 'TIGRA 2J']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'VARDI', 'name' => 'VARDI 1U']);
        DB::table('stars')->insert([ 'airport_id' => '32', 'runway' => '35', 'point' => 'YNN', 'name' => 'YNN 1U']);
        DB::table('stars')->insert([ 'airport_id' => '34', 'runway' => '14', 'point' => 'ASIMI', 'name' => 'ASIMI 1J']);
        DB::table('stars')->insert([ 'airport_id' => '34', 'runway' => '14', 'point' => 'GILOS', 'name' => 'GILOS 1J']);
        DB::table('stars')->insert([ 'airport_id' => '34', 'runway' => '32', 'point' => 'GILOS', 'name' => 'GILOS 1L']);
        DB::table('stars')->insert([ 'airport_id' => '34', 'runway' => '14', 'point' => 'KOPAR', 'name' => 'KOPAR 2J']);
        DB::table('stars')->insert([ 'airport_id' => '34', 'runway' => '32', 'point' => 'KOPAR', 'name' => 'KOPAR 2L']);
        DB::table('stars')->insert([ 'airport_id' => '34', 'runway' => '14', 'point' => 'LARKI', 'name' => 'LARKI 2H']);
        DB::table('stars')->insert([ 'airport_id' => '34', 'runway' => '32', 'point' => 'LARKI', 'name' => 'LARKI 2L']);
        DB::table('stars')->insert([ 'airport_id' => '34', 'runway' => '14', 'point' => 'USINI', 'name' => 'USINI 2H']);
        DB::table('stars')->insert([ 'airport_id' => '34', 'runway' => '32', 'point' => 'USINI', 'name' => 'USINI 2K']);
        DB::table('stars')->insert([ 'airport_id' => '36', 'runway' => '35L', 'point' => 'PLH', 'name' => 'PLH 1G']);
        DB::table('stars')->insert([ 'airport_id' => '36', 'runway' => '35L', 'point' => 'RESPA', 'name' => 'RESPA 1G']);
        DB::table('stars')->insert([ 'airport_id' => '36', 'runway' => '35L', 'point' => 'SOKRI', 'name' => 'SOKRI 1G']);
        DB::table('stars')->insert([ 'airport_id' => '38', 'runway' => '14', 'point' => 'ARA', 'name' => 'ARA 2N']);
        DB::table('stars')->insert([ 'airport_id' => '38', 'runway' => '32', 'point' => 'ARA', 'name' => 'ARA 3J']);
        DB::table('stars')->insert([ 'airport_id' => '38', 'runway' => '14', 'point' => 'ASTUS', 'name' => 'ASTUS 1N']);
        DB::table('stars')->insert([ 'airport_id' => '38', 'runway' => '32', 'point' => 'ASTUS', 'name' => 'ASTUS 1P']);
        DB::table('stars')->insert([ 'airport_id' => '38', 'runway' => '14', 'point' => 'LASKO', 'name' => 'LASKO 1N']);
        DB::table('stars')->insert([ 'airport_id' => '38', 'runway' => '32', 'point' => 'LASKO', 'name' => 'LASKO 1P']);
        DB::table('stars')->insert([ 'airport_id' => '39', 'runway' => '02', 'point' => 'IXIMA', 'name' => 'IXIMA 1B']);
        DB::table('stars')->insert([ 'airport_id' => '39', 'runway' => '20', 'point' => 'IXIMA', 'name' => 'IXIMA 1C']);
        DB::table('stars')->insert([ 'airport_id' => '39', 'runway' => '02', 'point' => 'SOKRI', 'name' => 'SOKRI 1B']);
        DB::table('stars')->insert([ 'airport_id' => '39', 'runway' => '20', 'point' => 'SOKRI', 'name' => 'SOKRI 1C']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'BAVES', 'name' => 'BAVES 2L','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'BAVES', 'name' => 'BAVES 1A','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'EPALO', 'name' => 'EPALO 2L','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'EPALO', 'name' => 'EPALO 1A','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'LABUX', 'name' => 'LABUX 2L','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'LABUX', 'name' => 'LABUX 1A','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'NAVUS', 'name' => 'NAVUS 2L','entry_flight_level' => 'FL110']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'NAVUS', 'name' => 'NAVUS 1A','entry_flight_level' => 'FL110']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'OTREX', 'name' => 'OTREX 2L','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'OTREX', 'name' => 'OTREX 3A','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'SIT', 'name' => 'SIT 2L','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'SIT', 'name' => 'SIT 2A','entry_flight_level' => 'FL140']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'TIPUS', 'name' => 'TIPUS 2L','entry_flight_level' => 'FL150']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '09', 'point' => 'XAVIS', 'name' => 'XAVIS 2L','entry_flight_level' => 'FL110']);
        DB::table('stars')->insert([ 'airport_id' => '41', 'runway' => '27', 'point' => 'XAVIS', 'name' => 'XAVIS 1A','entry_flight_level' => 'FL110']);
        DB::table('stars')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'GARTA', 'name' => 'GARTA 1E']);
        DB::table('stars')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'GARTA', 'name' => 'GARTA 1C']);
        DB::table('stars')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'KRK', 'name' => 'KRK 1E']);
        DB::table('stars')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'KRK', 'name' => 'KRK 1C']);
        DB::table('stars')->insert([ 'airport_id' => '42', 'runway' => '14', 'point' => 'ROTSA', 'name' => 'ROTSA 1E']);
        DB::table('stars')->insert([ 'airport_id' => '42', 'runway' => '32', 'point' => 'ROTSA', 'name' => 'ROTSA 1C']);
        DB::table('stars')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'LMO', 'name' => 'LMO']);
        DB::table('stars')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'LUPIS', 'name' => 'LUPIS']);
        DB::table('stars')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'MARIK', 'name' => 'MARIK']);
        DB::table('stars')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'PANOX', 'name' => 'PANOX']);
        DB::table('stars')->insert([ 'airport_id' => '44', 'runway' => '01', 'point' => 'PIPEN', 'name' => 'PIPEN']);
        DB::table('stars')->insert([ 'airport_id' => '45', 'runway' => '36', 'point' => 'EGN', 'name' => 'EGN']);
        DB::table('stars')->insert([ 'airport_id' => '45', 'runway' => '36', 'point' => 'I36', 'name' => 'I36-W']);
        DB::table('stars')->insert([ 'airport_id' => '45', 'runway' => '36', 'point' => 'R21', 'name' => 'R213N']);
        DB::table('stars')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'EVIKO', 'name' => 'EVIKO 1C']);
        DB::table('stars')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'GARTA', 'name' => 'GARTA 1H']);
        DB::table('stars')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'LUSES', 'name' => 'LUSES 1H']);
        DB::table('stars')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'PELI', 'name' => 'PELI 1C']);
        DB::table('stars')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'TGG', 'name' => 'TGG 2H']);
        DB::table('stars')->insert([ 'airport_id' => '46', 'runway' => '26', 'point' => 'VAXUS', 'name' => 'VAXUS 1H']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'ABLON', 'name' => 'ABLON 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'ABLON', 'name' => 'ABLON 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'ABLON', 'name' => 'ABLON 1B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'ABLON', 'name' => 'ABLON 1B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'ASTOV', 'name' => 'ASTOV 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'ASTOV', 'name' => 'ASTOV 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'ASTOV', 'name' => 'ASTOV 1B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'ASTOV', 'name' => 'ASTOV 1B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'BADEL', 'name' => 'BADEL 3C','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'BADEL', 'name' => 'BADEL 3C','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'KEPIR', 'name' => 'KEPIR 2C','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'KEPIR', 'name' => 'KEPIR 2C','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'KEPIR', 'name' => 'KEPIR 1A','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'KEPIR', 'name' => 'KEPIR 1A','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'NEMES', 'name' => 'NEMES 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'NEMES', 'name' => 'NEMES 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'NEMES', 'name' => 'NEMES 1B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'NEMES', 'name' => 'NEMES 1B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'NEVRA', 'name' => 'NEVRA 2C','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'NEVRA', 'name' => 'NEVRA 2C','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'NEVRA', 'name' => 'NEVRA 1A','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'NEVRA', 'name' => 'NEVRA 1A','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'OMIRO', 'name' => 'OMIRO 1A']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'OMIRO', 'name' => 'OMIRO 1A']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'PIKAD', 'name' => 'PIKAD 1C']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'PIKAD', 'name' => 'PIKAD 1C']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'PIKAD', 'name' => 'PIKAD 1B']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'PIKAD', 'name' => 'PIKAD 1B']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'RILIN', 'name' => 'RILIN 1C']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'RILIN', 'name' => 'RILIN 1C']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'RILIN', 'name' => 'RILIN 1B']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'RILIN', 'name' => 'RILIN 1B']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'SOREV', 'name' => 'SOREV 1C','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'SOREV', 'name' => 'SOREV 1C','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'SOREV', 'name' => 'SOREV 1B','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'SOREV', 'name' => 'SOREV 1B','entry_flight_level' => 'FL180']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'VARIX', 'name' => 'VARIX 2C','entry_flight_level' => 'FL200']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'VARIX', 'name' => 'VARIX 2C','entry_flight_level' => 'FL200']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'VARIX', 'name' => 'VARIX 1A','entry_flight_level' => 'FL200']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'VARIX', 'name' => 'VARIX 1A','entry_flight_level' => 'FL200']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'VELOP', 'name' => 'VELOP 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'VELOP', 'name' => 'VELOP 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'VELOP', 'name' => 'VELOP 1B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'VELOP', 'name' => 'VELOP 1B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03L', 'point' => 'XORKI', 'name' => 'XORKI 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '03R', 'point' => 'XORKI', 'name' => 'XORKI 1C','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21R', 'point' => 'XORKI', 'name' => 'XORKI 2B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '48', 'runway' => '21L', 'point' => 'XORKI', 'name' => 'XORKI 2B','entry_flight_level' => 'FL170']);
        DB::table('stars')->insert([ 'airport_id' => '49', 'runway' => '07', 'point' => 'GOLDO', 'name' => 'GOLDO 1A']);
        DB::table('stars')->insert([ 'airport_id' => '49', 'runway' => '25', 'point' => 'GOLDO', 'name' => 'GOLDO']);
        DB::table('stars')->insert([ 'airport_id' => '49', 'runway' => '07', 'point' => 'IDILO', 'name' => 'IDILO 1A']);
        DB::table('stars')->insert([ 'airport_id' => '49', 'runway' => '07', 'point' => 'LMO', 'name' => 'LMO 1A']);
        DB::table('stars')->insert([ 'airport_id' => '49', 'runway' => '25', 'point' => 'LMO', 'name' => 'LMO']);
        DB::table('stars')->insert([ 'airport_id' => '49', 'runway' => '07', 'point' => 'PEREN', 'name' => 'PEREN']);
        DB::table('stars')->insert([ 'airport_id' => '49', 'runway' => '25', 'point' => 'PEREN', 'name' => 'PEREN']);
    }
}
